"""Reviewed alternate racial traits using upstream replacement FACTs and pools."""
import argparse
import json
import re

from spheres import DATA
from spheres_catalog_source import SNAPSHOTS

OUTPUT = DATA / 'spheres_alternate_racial_traits.lst'
# Each replacement name is an existing core-essentials FACT, not a new pool.
OPTIONS = (
    ('Elf', 'Dreamless Sleep', ('ElvenImmunities',), 'Scout - Somnambulance'),
    ('Half-Elf', 'Dreamless Sleep', ('ElvenImmunities',), 'Scout - Somnambulance'),
    ('Halfling', 'Clever Combatant', ('Fearless', 'HalflingLuck'), 'Scoundrel Sphere'),
    ('Half-Orc', 'Brutally Trained', ('Intimidating', 'WeaponFamiliarity'), 'Equipment - Orc Heritage'),
    ('Half-Orc', 'Trained Berserk', ('OrcFerocity',), 'Berserker Sphere'),
    ('Dwarf', 'Dwarven Battle Training', ('DefensiveTraining', 'Hatred', 'WeaponFamiliarity'), 'Equipment - Dwarven Heritage'),
    ('Elf', 'Elven Ancestral Master', ('KeenSenses', 'WeaponFamiliarity'), 'Equipment - Elvish Heritage'),
    ('Halfling', 'Sling Lord', ('KeenSenses', 'WeaponFamiliarity'), 'Equipment - Halfling Heritage'),
    ('Dwarf', 'Superior Dwarven Make', ('WeaponFamiliarity',), 'Tinker Sphere'),
    ('Elf', 'Refined Ingenuity', ('ElvenMagic',), 'Tinker Sphere'),
    ('Gnome', 'Gnomish Tinkering', ('KeenSenses',), 'Tinker Sphere'),
    ('Gnome', 'Alchemical Training', ('GnomeMagic',), 'Alchemy Sphere'),
    ('Human', 'Titan of Industry', ('BonusFeat',), 'Tinker Sphere'),
)


def source_trait(race, name):
    source = json.loads((SNAPSHOTS / 'alternate-racial-traits.json').read_text())
    section = next(row for row in source['sections']
                   if row['heading'] == race and row['anchor'])
    # Traits on this page are paragraphs rather than TOC headings.
    paragraphs = re.split(r'\n(?=[A-Z][^\n:]{1,65}(?:\s*\[[^]]+\])?:|Titan of Industry \[)', section['text'])
    matches = [p for p in paragraphs if re.match(re.escape(name) + r'(?:\s*\[[^]]+\])?[: ]', p)]
    if len(matches) != 1:
        raise ValueError('Ambiguous racial source: ' + race + ' / ' + name)
    return matches[0], source['url'] + '#' + section['anchor']


def build():
    rows = ['# Generated by tools/spheres_racial.py; upstream racial replacement categories.']
    for race, name, replacements, grant in OPTIONS:
        body, url = source_trait(race, name)
        # The optional utility-talent trade is a separate unimplemented choice.
        if name == 'Titan of Industry':
            body = body.split('Special:')[0]
        key = race + ' ~ Spheres ' + name
        facts = [race.replace('-', '') + '_Replace' + replacement for replacement in replacements]
        tags = [name, 'KEY:' + key, 'CATEGORY:Special Ability',
                'TYPE:RacialTraits.' + race + ' Racial Trait.SpecialQuality',
                'PRERACE:1,' + race,
                'PREMULT:1,[PREABILITY:1,CATEGORY=Special Ability,' + key +
                '],[!PREFACT:1,ABILITIES,' + ','.join(f + '=true' for f in facts) + ']',
                'COST:0', *['FACT:' + f + '|true' for f in facts],
                'ABILITY:Spheres Combat Talent|AUTOMATIC|' + grant,
                'DESC:' + ' '.join(body.replace('|', '/').replace('%', ' percent').split()),
                'SOURCEPAGE:' + url]
        if name == 'Dreamless Sleep':
            tags += ['DEFINE:SPHERES_SCOUT_SOMNAMBULANCE_COUNT|0',
                     'DEFINE:SPHERES_SCOUT_TALENTS|0']
        rows.append('\t'.join(tags))
    return '\n'.join(rows) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    output = build()
    if args.write:
        OUTPUT.write_text(output)
    elif OUTPUT.read_text() != output:
        raise ValueError('Stale alternate racial traits')
    print('PASS: reviewed racial replacement records')


if __name__ == '__main__':
    main()