"""Generate power-only Incanter adapters for pinned Core sorcerer bloodlines."""
import argparse
import re
from spheres_incanter_domains import CORE, ROOT

OUTPUT = ROOT / "data/spheres/spheres_incanter_bloodlines.lst"


def render(core=CORE):
    result = ["# Generated by tools/spheres_incanter_bloodlines.py. Powers only; no arcana, spells or feats.",
              "# Incanter rules: https://spheresofpower.wikidot.com/incanter; checked 2026-09-22."]
    for line in (core / "cr_abilities_class.lst").read_text(encoding="utf-8").splitlines():
        fields = [field.strip() for field in line.split("\t") if field.strip()]
        if "CATEGORY:Sorcerer Bloodline" not in fields:
            continue
        name = fields[0].removesuffix(" Bloodline")
        purchase = f"Sorcerer Bloodline ({name})"
        result.append("\t".join([
            purchase, "CATEGORY:Incanter Specialization", "TYPE:IncanterSpecialization",
            "COST:2", "PREVAREQ:SPHERES_INCANTER_LEVEL,1",
            "PREVARLT:SPHERES_INCANTER_BLOODLINES,1",
            "DEFINE:SPHERES_INCANTER_BLOODLINES|0",
            "BONUS:VAR|SPHERES_INCANTER_BLOODLINES|1",
            "BONUS:VAR|SPHERES_INCANTER_SPECIALIZATION_POINTS|2",
            f"DESC:Purchase {name} bloodline powers; activate in specialization order.",
        ]))
        active = [f"Active {purchase}", "CATEGORY:Incanter Active Specialization",
                  "TYPE:IncanterActive", "COST:2",
                  f"PREABILITY:1,CATEGORY=Incanter Specialization,{purchase}",
                  "DEFINE:BloodlineLVL|0", "DEFINE:BloodlineProgressionLVL|0",
                  "DEFINE:BloodlinePowerTimes|0", "DEFINE:Sorcerer_Spells_StatBonus|0",
                  "BONUS:VAR|BloodlineLVL,BloodlineProgressionLVL|SPHERES_INCANTER_LEVEL|TYPE=Base",
                  "BONUS:VAR|BloodlinePowerTimes|3+max(CHA,SPHERES_CASTING_ABILITY)|TYPE=Base",
                  "BONUS:VAR|Sorcerer_Spells_StatBonus|max(CHA,SPHERES_CASTING_ABILITY)|TYPE=Base",
                  f"DESC:{name} bloodline powers only. Use Incanter level and the higher of Charisma or casting modifier."]
        for field in fields:
            if field.startswith("ABILITY:Special Ability|AUTOMATIC|Sorcerer Bloodline ~ "):
                active.append(field)
            if field.startswith("BONUS:VAR|Sorcerer_") and not any(
                    excluded in field for excluded in ("BloodlineArcana", "BloodlineSpells", "BloodlineClassSkill")):
                # Class replacement variables belong to the Sorcerer class, which
                # this single-class character does not have. Its unmodified powers
                # are granted directly, with the same level thresholds.
                field = re.sub(r"Sorcerer_CF_Bloodline\w+==0", "1==1", field)
                field = field.replace("if(1==1,1,0)", "1")
                field = re.sub(r"if\(\(1==1&&[^>]+>=(\d+)\),1,0\)",
                               r"if(SPHERES_INCANTER_LEVEL>=\1,1,0)", field)
                field = field.replace("+BloodlinePower1TimesBonus", "")
                active.append(field)
        result.append("\t".join(active))
    if len(result) != 22:
        raise ValueError("Pinned Core must supply exactly ten bloodlines")
    return "\n".join(result) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = render()
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != text:
            parser.exit(1, "Incanter bloodline adapters are stale\n")
        print("PASS: ten Incanter bloodline adapters match pinned Core data")
    else:
        OUTPUT.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()