"""Build PF1 Spheres trait records from pinned Power/Might trait pages."""
import argparse
import json
import re

from spheres_catalog_source import ROOT, SNAPSHOTS
from spheres_catalog_lst import text
from spheres_feats import Prerequisites

DATA = ROOT / "data/spheres"
SOURCES = ("traits", "practitioner-traits")
GROUPS = {"Campaign": "CampaignTrait", "Combat": "CombatTrait",
          "Equipment": "EquipmentTrait", "Faith": "FaithTrait",
          "Magic": "MagicTrait", "Race": "RaceTrait", "Region": "RegionalTrait",
          "Religion": "ReligionTrait", "Social": "SocialTrait",
          "Tradition": "TraditionTrait", "Legacy": "LegacyTrait"}


def inventory():
    """Use current headings first, then distinct traits in the Original appendix."""
    rows = {}
    for slug in SOURCES:
        source = json.loads((SNAPSHOTS / (slug + ".json")).read_text())
        group = None
        for section in source["sections"]:
            if not section["anchor"] and not (slug == "traits" and section["level"]):
                continue
            heading, level = section["heading"], section["level"]
            if slug == "traits" and heading.startswith("Character Legacies"):
                group = "Legacy"
                continue
            if level in (1, 2) and not heading.startswith("Optional Rule"):
                group = re.sub(r"\s*\(.*", "", heading).removesuffix(" Traits")
                if group == "Racial":
                    group = "Race"
                continue
            if (group not in GROUPS and group != "Drawback") or level != 4:
                continue
            if group == "Legacy":
                # Legacy headings describe a retired hero; the actual trait is
                # named in the final paragraph, not in the heading.
                match = re.search(r"(?:^|\n)([^\n:]+?)\s*\[([^\]]*\bLegacy\b[^\]]*)\]:\s*(.*)", section["text"], re.S)
                if not match:
                    raise ValueError("Unparsed legacy trait: " + heading)
                name, body = match[1].strip(), match[3].strip()
                heading = name + " [" + match[2] + "]"
            else:
                name = re.sub(r"\s*\[[^]]+\]", "", heading)
                name = re.sub(r"\s*\((?:combat|equipment|region|religion|social|faith|magic|race)\)", "", name, flags=re.I)
                name = re.sub(r"\s*\((?:requires |arcane,|divine,|psychic,).*", "", name, flags=re.I).strip()
                body = section["text"].strip()
            if not name or not body:
                raise ValueError("Empty trait: " + heading)
            identity = name.casefold().replace("’", "'")
            url = source["url"] + "#" + section["anchor"]
            if identity in rows:
                # Some entries occur on both Power and Might pages with the same
                # name: keep the first current occurrence, retain both sources.
                rows[identity]["sources"].append(url)
                continue
            rows[identity] = {"name": name, "group": group, "heading": heading,
                              "text": body, "sources": [url]}
    return sorted(rows.values(), key=lambda row: row["name"].casefold())


def requirements(row, parser):
    """Compile explicit source prerequisites, failing closed on unrecognized clauses."""
    requirements = re.findall(r"Prerequisites?:\s*(.*?)(?=\n|Benefits?:|$)", row["text"], re.I)
    requires = re.search(r"\(requires (.*)\)(?:\s*\[[^]]+\])?$", row["heading"], re.I)
    if requires:
        requirements.append(requires[1])
    tags, missing = [], []
    for requirement in requirements:
        found, unknown = parser.compile("Prerequisite: " + requirement + "\nBenefit: Trait.")
        tags.extend(found)
        missing.extend(unknown)
    return list(dict.fromkeys(tags)), missing


def build():
    rows = inventory()
    parser = Prerequisites([])
    overrides = json.loads((DATA / "trait-mechanics.json").read_text())
    generated = ["# Generated by tools/spheres_traits.py; OGC: catalog-OGL.txt"]
    approval = ["# Manual approval only for source prerequisites not modeled by PCGen."]
    drawback = ["# A drawback spends one shared PF1 trait slot and grants two: net +1."]
    for row in rows:
        name, group = row["name"], row["group"]
        key = "Spheres Trait ~ " + name.replace(",", "")
        row["key"] = key
        prereqs, missing = requirements(row, parser)
        row["prerequisites"] = prereqs
        tags = [key, "CATEGORY:Special Ability"]
        if group == "Drawback":
            # A drawback is picked from the common pool: two slots granted
            # less one slot spent leaves one additional ordinary trait.
            tags += ["TYPE:Trait.SpheresDrawbackTrait", "!PREABILITY:1,CATEGORY=Special Ability,TYPE.SpheresDrawbackTrait",
                     "BONUS:VAR|Pool_Traits|2"]
        else:
            trait_type = GROUPS[group]
            tags += ["TYPE:Trait.BasicTrait." + trait_type + ".SpheresTrait",
                     "PREMULT:1,[PREVARGTEQ:BypassTraitRestriction,1],[!PREABILITY:1,CATEGORY=Special Ability,TYPE." + trait_type + "]"]
        tags.extend(prereqs)
        if group in ("Campaign", "Legacy", "Tradition"):
            missing.append("GM approval and setting/tradition eligibility for " + group + " trait")
        row["unresolved_prerequisites"] = missing
        if missing:
            approved = "Reviewed - " + key
            tags.append("PREABILITY:1,CATEGORY=Spheres Trait Adjudication," + approved)
            approval.append("\t".join([approved, "CATEGORY:Spheres Trait Adjudication", "COST:0",
                "DESC:Approve unsupported prerequisites manually; does not grant a trait or its effects: " + text("; ".join(missing))]))
        mechanics = overrides.get(name, [])
        row["mechanics"] = mechanics
        tags.extend(mechanics)
        tags.extend(["DESC:" + text(row["text"]) + " Automation is partial; see docs/spheres-traits.md.",
                     "SOURCEPAGE:" + row["sources"][0]])
        (drawback if group == "Drawback" else generated).append("\t".join(tags))
    if len({r["key"] for r in rows}) != len(rows):
        raise ValueError("Trait keys collide after sanitizing PCGen punctuation")
    if set(overrides) - {r["name"] for r in rows}:
        raise ValueError("Unknown trait mechanics: " + ", ".join(sorted(set(overrides) - {r["name"] for r in rows})))
    return {"trait-catalog.json": json.dumps(rows, indent=2, ensure_ascii=False) + "\n",
            "spheres_traits.lst": "\n".join(generated) + "\n",
            "spheres_trait_drawbacks.lst": "\n".join(drawback) + "\n",
            "spheres_trait_adjudication.lst": "\n".join(approval) + "\n",
            "spheres_categories_traits.lst": "ABILITYCATEGORY:Spheres Trait Adjudication\tCATEGORY:Spheres Trait Adjudication\tEDITABLE:YES\tEDITPOOL:NO\tPOOL:0\tFRACTIONALPOOL:NO\tVISIBLE:YES\tPLURAL:Manual Trait Approvals\tDISPLAYLOCATION:Traits\n"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    outputs = build()
    for filename, content in outputs.items():
        path = DATA / filename
        if args.write:
            path.write_text(content, encoding="utf-8")
        elif not path.exists() or path.read_text() != content:
            raise SystemExit("Stale trait catalog: " + str(path))
    rows = json.loads(outputs["trait-catalog.json"])
    print(f'{len(rows)} source traits; {sum(bool(r["unresolved_prerequisites"]) for r in rows)} require prerequisite review')


if __name__ == "__main__":
    main()