"""Source-backed prestige adapters; independent casting is not aligned-class advancement."""
import argparse
import json

from spheres import DATA
from spheres_catalog_source import SNAPSHOTS


def tempestarii():
    source = json.loads((SNAPSHOTS / 'tempestarii.json').read_text())
    sections = {r['heading']: r for r in source['sections']}
    features = {1: ('Rapid Weather',), 2: ('Ship Smasher',), 3: ('Grand Weather',),
                4: ('Ship Killer',), 5: ('Deadly Weather', 'Instant Weather')}
    classes = ['# Generated by tools/spheres_prestige.py from pinned Tempestarii rules.',
               '\t'.join(['CLASS:Tempestarii', 'HD:6', 'TYPE:Prestige.PC', 'MAXLEVEL:5',
                          'STARTSKILLPTS:4',
                          'CSKILL:Fly|Intimidate|Knowledge (Geography)|Knowledge (Nature)|Perception|TYPE=Profession|Spellcraft|Survival',
                          'PREVARGTEQ:SPHERES_CL_WEATHER,5',
                          'PREABILITY:1,CATEGORY=Spheres Magic Talent,Weather Sphere',
                          'PRESKILL:1,Knowledge (Nature)=5',
                          'BONUS:COMBAT|BASEAB|floor(CL/2)|TYPE=Base.REPLACE',
                          'BONUS:SAVE|BASE.Fortitude,BASE.Reflex|floor((CL+1)/3)',
                          'BONUS:SAVE|BASE.Will|floor((CL+1)/2)',
                          'DEFINE:SPHERES_TEMPESTARII_LEVEL|0',
                          'BONUS:VAR|SPHERES_TEMPESTARII_LEVEL|CL',
                          'BONUS:VAR|SPHERES_CASTER_LEVEL,SPHERES_MAGIC_SKILL_BONUS,SPHERES_SPELL_POOL_LEVELS|CL',
                          'SOURCEPAGE:' + source['url']])]
    abilities = ['# Generated by tools/spheres_prestige.py; conditional weather effects remain sheet rules.']
    for level, names in features.items():
        tags = [str(level), 'BONUS:VAR|SPHERES_MAGIC_TALENTS|1']
        if level == 1:
            tags.append('ABILITY:Special Ability|AUTOMATIC|Spheres Casting Core')
        for name in names:
            key = 'Tempestarii ' + name
            tags.append('ABILITY:Special Ability|AUTOMATIC|' + key)
            row = sections[name]
            body = row['text'].split('\n| Spheres of Power')[0]
            body = ' '.join(body.replace('|', '/').replace('%', ' percent').split())
            ability = [key, 'CATEGORY:Special Ability', 'TYPE:TempestariiClassFeature',
                       'DESC:' + body, 'SOURCEPAGE:' + source['url'] + '#' + row['anchor']]
            if name == 'Rapid Weather':
                ability += ['DEFINE:SPHERES_TEMPESTARII_WEATHER_STEPS|0',
                            'BONUS:VAR|SPHERES_TEMPESTARII_WEATHER_STEPS|1+SPHERES_TEMPESTARII_LEVEL']
            abilities.append('\t'.join(ability))
        classes.append('\t'.join(tags))
    return {'spheres_tempestarii_class.lst': '\n'.join(classes) + '\n',
            'spheres_tempestarii_features.lst': '\n'.join(abilities) + '\n'}


def forest_lord():
    source = json.loads((SNAPSHOTS / 'forest-lord.json').read_text())
    sections = {r['heading']: r for r in source['sections']}
    strength = 'Forest\u2019s Strength'
    features = {1: ('Cryptwood Connection', 'Favored Terrain', 'Master Leaper'),
                2: (strength,), 3: ('Master Geomancer',), 4: (strength,),
                5: ('Favored Terrain', 'Forest Heart')}
    classes = ['# Generated by tools/spheres_prestige.py from pinned Forest Lord rules.',
               '\t'.join(['CLASS:Forest Lord', 'HD:6', 'TYPE:Prestige.PC', 'MAXLEVEL:5',
                          'STARTSKILLPTS:4',
                          'CSKILL:Climb|Handle Animal|Knowledge (Geography)|Knowledge (Nature)|Perception|Ride|Spellcraft|Survival|Swim|Use Magic Device',
                          'PREVARGTEQ:SPHERES_CL_NATURE,5',
                          'PREABILITY:1,CATEGORY=Spheres Magic Talent,Nature Sphere',
                          'PREABILITY:1,CATEGORY=Spheres Nature Package,Nature Package - Plant',
                          'PRESKILL:2,Acrobatics=5,Knowledge (Nature)=5',
                          'PRESKILL:1,Survival=5',
                          'BONUS:COMBAT|BASEAB|floor(CL/2)|TYPE=Base.REPLACE',
                          'BONUS:SAVE|BASE.Fortitude,BASE.Reflex,BASE.Will|floor((CL+1)/2)',
                          'DEFINE:SPHERES_FOREST_LORD_LEVEL|0',
                          'BONUS:VAR|SPHERES_FOREST_LORD_LEVEL|CL',
                          'BONUS:VAR|SPHERES_CASTER_LEVEL,SPHERES_MAGIC_SKILL_BONUS,SPHERES_SPELL_POOL_LEVELS|CL',
                          'SOURCEPAGE:' + source['url']])]
    abilities = ['# Generated by tools/spheres_prestige.py; conditional cryptwood and terrain effects remain sheet rules.']
    for level, names in features.items():
        tags = [str(level), 'BONUS:VAR|SPHERES_MAGIC_TALENTS|1']
        if level == 1:
            tags.append('ABILITY:Special Ability|AUTOMATIC|Spheres Casting Core')
        for name in names:
            key = 'Forest Lord ' + name
            tags.append('ABILITY:Special Ability|AUTOMATIC|' + key)
            row = sections[name]
            body = row['text'].split('\n| Spheres of Power')[0]
            body = ' '.join(body.replace('|', '/').replace('%', ' percent').split())
            ability = [key, 'CATEGORY:Special Ability', 'TYPE:ForestLordClassFeature',
                       'DESC:' + body, 'SOURCEPAGE:' + source['url'] + '#' + row['anchor']]
            if name == 'Cryptwood Connection':
                ability += ['DEFINE:SPHERES_FOREST_LORD_CRYPTWOOD_DR|0',
                            'BONUS:VAR|SPHERES_FOREST_LORD_CRYPTWOOD_DR|SPHERES_FOREST_LORD_LEVEL',
                            'DEFINE:SPHERES_FOREST_LORD_CRYPTWOOD_SAVE|0',
                            'BONUS:VAR|SPHERES_FOREST_LORD_CRYPTWOOD_SAVE|SPHERES_FOREST_LORD_LEVEL']
            if name == 'Master Leaper':
                ability += ['DEFINE:SPHERES_FOREST_LORD_JUMP_BONUS|0',
                            'BONUS:VAR|SPHERES_FOREST_LORD_JUMP_BONUS|2*SPHERES_FOREST_LORD_LEVEL']
            if name == strength:
                ability += ['DEFINE:SPHERES_FOREST_LORD_STRENGTH_INHERENT|if(SPHERES_FOREST_LORD_LEVEL>=5,6,if(SPHERES_FOREST_LORD_LEVEL>=4,4,2))',
                            'DEFINE:SPHERES_FOREST_LORD_CLIMB_SPEED|if(SPHERES_FOREST_LORD_LEVEL>=5,40,if(SPHERES_FOREST_LORD_LEVEL>=4,30,20))']
            if name == 'Forest Heart':
                ability += ['DEFINE:SPHERES_FOREST_LORD_HEART_STRENGTH|6',
                            'DEFINE:SPHERES_FOREST_LORD_HEART_CLIMB|40']
            abilities.append('\t'.join(ability))
        classes.append('\t'.join(tags))
    return {'spheres_forest-lord_class.lst': '\n'.join(classes) + '\n',
            'spheres_forest-lord_features.lst': '\n'.join(abilities) + '\n'}


def waking_sleeper():
    source = json.loads((SNAPSHOTS / 'waking-sleeper.json').read_text())
    sections = {r['heading']: r for r in source['sections']}
    features = {1: ('Mark of the Master', 'Recall', 'Sleeper Training'),
                2: ('Catatonia',), 3: ('Deep Conditioning',),
                4: ('Regimented Thought',), 5: ('Perfect Clarity',)}
    classes = ['# Generated by tools/spheres_prestige.py from pinned Waking Sleeper rules.',
               '\t'.join(['CLASS:Waking Sleeper', 'HD:10', 'TYPE:Prestige.PC', 'MAXLEVEL:5',
                          'STARTSKILLPTS:4',
                          'CSKILL:Acrobatics|Climb|TYPE=Craft|Handle Animal|Knowledge (Nobility)|Perception|TYPE=Profession|Ride|Swim|Use Magic Device',
                          'PREVARGTEQ:BAB,3',
                          'PRESKILL:1,Knowledge (Nobility)=5',
                          'BONUS:COMBAT|BASEAB|CL|TYPE=Base.REPLACE',
                          'BONUS:SAVE|BASE.Fortitude|floor(CL/3)',
                          'BONUS:SAVE|BASE.Reflex,BASE.Will|floor((CL+1)/2)',
                          'DEFINE:SPHERES_WAKING_SLEEPER_LEVEL|0',
                          'BONUS:VAR|SPHERES_WAKING_SLEEPER_LEVEL|CL',
                          'ABILITY:Internal|AUTOMATIC|Weapon Prof ~ Simple|Weapon Prof ~ Martial',
                          'SOURCEPAGE:' + source['url']])]
    abilities = ['# Generated by tools/spheres_prestige.py; recall activation, feat-pool choices and rest recovery remain table-resolved.']
    for level, names in features.items():
        tags = [str(level)]
        for name in names:
            key = 'Waking Sleeper ' + name
            tags.append('ABILITY:Special Ability|AUTOMATIC|' + key)
            row = sections[name + ' (Su)' if name in ('Mark of the Master', 'Regimented Thought') else name + ' (Ex)']
            body = row['text'].split('\n| Spheres of Power')[0]
            body = ' '.join(body.replace('|', '/').replace('%', ' percent').split())
            ability = [key, 'CATEGORY:Special Ability', 'TYPE:WakingSleeperClassFeature',
                       'DESC:' + body, 'SOURCEPAGE:' + source['url'] + '#' + row['anchor']]
            if name == 'Recall':
                ability += ['DEFINE:SPHERES_WAKING_RECALL_ROUNDS|2+2*SPHERES_WAKING_SLEEPER_LEVEL',
                            'DEFINE:SPHERES_WAKING_RECALL_STR|if(SPHERES_WAKING_SLEEPER_LEVEL>=5,6,2)',
                            'DEFINE:SPHERES_WAKING_RECALL_WILL|if(SPHERES_WAKING_SLEEPER_LEVEL>=5,6,if(SPHERES_WAKING_SLEEPER_LEVEL>=3,4,2))',
                            'DEFINE:SPHERES_WAKING_RECALL_FEATS|if(SPHERES_WAKING_SLEEPER_LEVEL>=5,5,if(SPHERES_WAKING_SLEEPER_LEVEL>=3,3,1))']
            if name == 'Catatonia':
                ability += ['DEFINE:SPHERES_WAKING_CATATONIA_REST_HP|SPHERES_WAKING_SLEEPER_LEVEL',
                            'DEFINE:SPHERES_WAKING_CATATONIA_ABILITY_DAMAGE|2']
            if name == 'Regimented Thought':
                ability += ['DEFINE:SPHERES_WAKING_REGIMENTED_DC|15']
            abilities.append('\t'.join(ability))
        classes.append('\t'.join(tags))
    return {'spheres_waking-sleeper_class.lst': '\n'.join(classes) + '\n',
            'spheres_waking-sleeper_features.lst': '\n'.join(abilities) + '\n'}


def archwizard():
    source = json.loads((SNAPSHOTS / 'spheres-archwizard.json').read_text())
    sections = {r['heading']: r for r in source['sections']}
    features = {1: ('Forgo Materials', 'Metamagic Enhancement',),
                2: ('Spellcasting Master', 'Arcane Servant',),
                3: ('Detect Expertise',), 4: ('Spell Echo',),
                5: ('Sphere-Like Ability', 'Epic Crafter',),
                6: ('Overcome Drawbacks',), 7: ('Shaped Area',),
                8: ('Selective Targets',), 9: ('Bypass Spell Resistance',),
                10: ('Archwizardry',)}
    classes = ['# Generated by tools/spheres_prestige.py from pinned Spheres Archwizard rules.',
               '\t'.join(['CLASS:Spheres Archwizard', 'HD:6', 'TYPE:Prestige.PC', 'MAXLEVEL:10',
                          'STARTSKILLPTS:2',
                          'CSKILL:Knowledge (Arcana)|Spellcraft|Use Magic Device',
                          'PREVARGTEQ:SPHERES_CASTER_LEVEL,5',
                          'BONUS:COMBAT|BASEAB|floor(CL/2)|TYPE=Base.REPLACE',
                          'BONUS:SAVE|BASE.Fortitude,BASE.Reflex|floor(CL/3)',
                          'BONUS:SAVE|BASE.Will|floor((CL+1)/2)',
                          'DEFINE:SPHERES_ARCHWIZARD_LEVEL|0',
                          'BONUS:VAR|SPHERES_ARCHWIZARD_LEVEL|CL',
                          'BONUS:VAR|SPHERES_CASTER_LEVEL,SPHERES_MAGIC_SKILL_BONUS,SPHERES_SPELL_POOL_LEVELS|CL',
                          'SOURCEPAGE:' + source['url']])]
    abilities = ['# Generated by tools/spheres_prestige.py; spell-point costs, crafting and trigger resolution remain table-resolved.']
    for level, names in features.items():
        tags = [str(level), 'BONUS:VAR|SPHERES_MAGIC_TALENTS|1']
        if level == 1:
            tags.append('ABILITY:Special Ability|AUTOMATIC|Spheres Casting Core')
        for name in names:
            key = 'Spheres Archwizard ' + name
            tags.append('ABILITY:Special Ability|AUTOMATIC|' + key)
            match = next(r for h, r in sections.items() if h.startswith(name))
            body = match['text'].split('\n| Ultimate')[0]
            body = ' '.join(body.replace('|', '/').replace('%', ' percent').split())
            ability = [key, 'CATEGORY:Special Ability', 'TYPE:SpheresArchwizardClassFeature',
                       'DESC:' + body, 'SOURCEPAGE:' + source['url'] + '#' + match['anchor']]
            if name == 'Forgo Materials':
                ability += ['DEFINE:SPHERES_ARCHWIZARD_RITUAL_GP|100*SPHERES_ARCHWIZARD_LEVEL']
            if name == 'Metamagic Enhancement':
                ability += ['DEFINE:SPHERES_ARCHWIZARD_METAMAGIC_REDUCTION|if(SPHERES_ARCHWIZARD_LEVEL>=10,3,if(SPHERES_ARCHWIZARD_LEVEL>=5,2,1))']
            if name == 'Spellcasting Master':
                ability += ['BONUS:SKILL|Knowledge (Arcana),Spellcraft,Use Magic Device|5|TYPE=Insight']
            if name == 'Spell Echo':
                ability += ['DEFINE:SPHERES_ARCHWIZARD_SPELL_ECHO_USES|floor(SPHERES_ARCHWIZARD_LEVEL/2)']
            if name == 'Selective Targets':
                ability += ['DEFINE:SPHERES_ARCHWIZARD_SELECTIVE_EXCLUDE|max(0,SPHERES_CASTING_ABILITY)']
            if name == 'Bypass Spell Resistance':
                ability += ['DEFINE:SPHERES_ARCHWIZARD_SR_REDUCTION|SPHERES_ARCHWIZARD_LEVEL',
                            'DEFINE:SPHERES_ARCHWIZARD_SR_ROUNDS|SPHERES_ARCHWIZARD_LEVEL']
            if name == 'Archwizardry':
                ability += ['DEFINE:SPHERES_ARCHWIZARD_ARCHWIZARDRY_USES|max(1,floor(SPHERES_CASTER_LEVEL/6))']
            abilities.append('\t'.join(ability))
        classes.append('\t'.join(tags))
    return {'spheres_archwizard_class.lst': '\n'.join(classes) + '\n',
            'spheres_archwizard_features.lst': '\n'.join(abilities) + '\n'}


def magemage():
    source = json.loads((SNAPSHOTS / 'magemage.json').read_text())
    sections = {r['heading']: r for r in source['sections']}
    features = {1: ('Aligned Class', 'Casting', 'Don Robes and Magecap'),
                2: ('Sagacity',), 3: ('Spellwrought Mark',),
                4: ('Knowledge Is My Sword',), 6: ('Wisdom Is My Orb',),
                8: ('Might Is My Scepter',), 10: ('Magic Is My Crown',)}

    def lookup(name):
        for suffix in (' (Ex)', ' (Su)', ''):
            if name + suffix in sections:
                return sections[name + suffix]
        raise KeyError(name)

    classes = ['# Generated by tools/spheres_prestige.py from pinned Magemage rules.',
               '\t'.join(['CLASS:Magemage', 'HD:8', 'TYPE:Prestige.PC', 'MAXLEVEL:10',
                          'STARTSKILLPTS:6',
                          'CSKILL:Knowledge (Arcana)|Spellcraft|Use Magic Device',
                          'PRECLASS:1,Mageknight=1',
                          'PRESKILL:1,Spellcraft=5',
                          'BONUS:COMBAT|BASEAB|floor(CL/2)|TYPE=Base.REPLACE',
                          'BONUS:SAVE|BASE.Fortitude,BASE.Reflex|floor((CL+1)/3)',
                          'BONUS:SAVE|BASE.Will|floor((CL+1)/2)',
                          'DEFINE:SPHERES_MAGEMAGE_LEVEL|0',
                          'BONUS:VAR|SPHERES_MAGEMAGE_LEVEL|CL',
                          'BONUS:VAR|SPHERES_CASTER_LEVEL,SPHERES_MAGIC_SKILL_BONUS,SPHERES_SPELL_POOL_LEVELS|CL',
                          'SOURCEPAGE:' + source['url']])]
    abilities = ['# Generated by tools/spheres_prestige.py; the knightknight archetype requirement and per-round '
                 'magecap use remain sheet-resolved.']
    for level in range(1, 11):
        names = features.get(level, ())
        tags = [str(level), 'BONUS:VAR|SPHERES_MAGIC_TALENTS|1']
        if level == 1:
            tags.append('ABILITY:Special Ability|AUTOMATIC|Spheres Casting Core')
        for name in names:
            key = 'Magemage ' + name
            tags.append('ABILITY:Special Ability|AUTOMATIC|' + key)
            row = lookup(name)
            body = row['text'].split('\n| ')[0]
            body = ' '.join(body.replace('|', '/').replace('%', ' percent').split())
            ability = [key, 'CATEGORY:Special Ability', 'TYPE:MagemageClassFeature',
                       'DESC:' + body, 'SOURCEPAGE:' + source['url'] + '#' + row['anchor']]
            if name == 'Casting':
                ability += ['DEFINE:SPHERES_MAGEMAGE_LOW_CASTER|1']
            if name == 'Sagacity':
                ability += ['DEFINE:SPHERES_MAGEMAGE_SAGACITY_BONUS|max(1,INT)']
            if name == 'Spellwrought Mark':
                ability += ['DEFINE:SPHERES_MAGEMAGE_SPELLWROUGHT_DIE|floor(SPHERES_MAGEMAGE_LEVEL/2)']
            if name == 'Knowledge Is My Sword':
                ability += ['DEFINE:SPHERES_MAGEMAGE_KNOWLEDGE_SWORD_BONUS|floor(SPHERES_MAGEMAGE_LEVEL/2)']
            if name == 'Wisdom Is My Orb':
                ability += ['DEFINE:SPHERES_MAGEMAGE_WISDOM_ORB_BONUS|floor(SPHERES_MAGEMAGE_LEVEL/2)']
            if name == 'Might Is My Scepter':
                ability += ['DEFINE:SPHERES_MAGEMAGE_MIGHT_SCEPTER_BONUS|floor(SPHERES_MAGEMAGE_LEVEL/2)']
            if name == 'Magic Is My Crown':
                ability += ['DEFINE:SPHERES_MAGEMAGE_CROWN_CL_BONUS|2']
            abilities.append('\t'.join(ability))
        classes.append('\t'.join(tags))
    return {'spheres_magemage_class.lst': '\n'.join(classes) + '\n',
            'spheres_magemage_features.lst': '\n'.join(abilities) + '\n'}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    files = tempestarii()
    files.update(forest_lord())
    files.update(waking_sleeper())
    files.update(archwizard())
    files.update(magemage())
    for name, content in files.items():
        path = DATA / name
        if args.write:
            path.write_text(content)
        elif path.read_text() != content:
            raise ValueError('Stale prestige data: ' + name)
    print('PASS: Tempestarii, Forest Lord, Waking Sleeper, Archwizard and Magemage generated progressions')


if __name__ == '__main__':
    main()