"""Render Incanter domain adapters from the pinned Core domain power records.

Only domain abilities and persistent domain bonuses are reused, never spells.
The output is first-party glue; original powers remain in the vendored source.
"""
from pathlib import Path
import argparse
import re

ROOT = Path(__file__).resolve().parents[1]
CORE = ROOT / "vendor/upstream/pcgen-6.08.00RC10/data/pathfinder/paizo/roleplaying_game/core_rulebook"
OUTPUT = ROOT / "data/spheres/spheres_incanter_domains.lst"


def render(core=CORE):
    domains = {}
    for line in (core / "cr_domains.lst").read_text(encoding="utf-8").splitlines():
        fields = [field.strip() for field in line.split("\t") if field.strip()]
        if not fields or fields[0].startswith("#") or fields[0].endswith(".MOD"):
            continue
        if any(field.startswith("ABILITY:Internal|AUTOMATIC|Core Domain ~ ") for field in fields):
            domains[fields[0]] = fields
    result = ["# Generated by tools/spheres_incanter_domains.py; no domain spells or deity requirement.",
              "# Incanter rules: https://spheresofpower.wikidot.com/incanter; checked 2026-09-22."]
    for name, fields in domains.items():
        if name == "Death (Pharasma)":
            continue  # This variant only replaces domain spells, which Incanter does not gain.
        variable = name.replace(" ", "")
        purchase = f"Cleric Domain ({name})"
        result.append("\t".join([
            purchase, "CATEGORY:Incanter Specialization", "TYPE:IncanterSpecialization",
            "COST:1", "PREVAREQ:SPHERES_INCANTER_LEVEL,1",
            "BONUS:VAR|SPHERES_INCANTER_SPECIALIZATION_POINTS|1",
            f"DESC:Purchase the {name} domain powers, without domain spells; activate in specialization order.",
        ]))
        active = [f"Active {purchase}", "CATEGORY:Incanter Active Specialization",
                  "TYPE:IncanterActive", "COST:1",
                  f"PREABILITY:1,CATEGORY=Incanter Specialization,{purchase}",
                  "DEFINE:DomainLVL|0", "DEFINE:DomainAbilityTriggerLVL|0",
                  "DEFINE:DomainPowerTimes|0",
                  "BONUS:VAR|DomainLVL,DomainAbilityTriggerLVL|SPHERES_INCANTER_LEVEL|TYPE=Base",
                  "BONUS:VAR|DomainPowerTimes|3+SPHERES_CASTING_ABILITY|TYPE=Base",
                  f"BONUS:VAR|Domain{variable}DC|SPHERES_CASTING_ABILITY-CHA",
                  f"DESC:{name} domain powers at Incanter level; use casting ability instead of Wisdom."]
        for field in fields[1:]:
            if field.startswith(("ABILITY:", "CSKILL:", "BONUS:")):
                # Domain-level bonuses use WIS directly in a few upstream records.
                active.append(re.sub(r"\bWIS\b", "SPHERES_CASTING_ABILITY", field))
        result.append("\t".join(active))
    if len(result) != 68:
        raise ValueError("Pinned Core source must supply exactly 33 domain adapters")
    return "\n".join(result) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = render()
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != text:
            parser.exit(1, "Incanter domain adapters are stale\n")
        print("PASS: 33 Incanter domain adapters match pinned Core data")
    else:
        OUTPUT.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()