"""Received Protection aegises, using the pinned Ultimate rules."""


def templates():
    effects = (
        ('Deflection', 'COMBAT|AC|1+floor(%CHOICE/5)|TYPE=Deflection'),
        ('Armored Magic - Armor', 'COMBAT|AC|3+floor(%CHOICE/5)|TYPE=Armor'),
        ('Armored Magic - Shield', 'COMBAT|AC|1+floor(%CHOICE/5)|TYPE=Shield'),
        ('Resistance', 'SAVE|ALL|1+floor(%CHOICE/4)|TYPE=Resistance'),
    )
    lines = ['# Generated by tools/spheres_catalog_lst.py; OGC: catalog-OGL.txt']
    for name, bonus in effects:
        lines.append('\t'.join([
            'Protection Effect - ' + name, 'VISIBLE:NO',
            'TEMPBONUS:ANYPC|' + bonus,
            'TEMPVALUE:MIN=1|MAX=100|TITLE=Choose the effect caster level',
            'TEMPDESC:Received ' + name + ' aegis. Enter caster level when cast, not recipient '
            'level. Lasts 1 hour per caster level unless modified. Remove when it ends. '
            'Target legality, spell resistance, Will saves, spell points, and duration are '
            'player-managed. Armored Magic applies against incorporeal attacks; resolve '
            'that exception at the table. This does not grant talents or casting permission.',
            'SOURCEPAGE:https://spheresofpower.wikidot.com/protection',
        ]))
    lines.append('\t'.join([
        'Protection Effect - Slippery', 'VISIBLE:NO',
        'TEMPBONUS:ANYPC|SKILL|Acrobatics,Escape Artist|2+floor(%CHOICE/5)|TYPE=Enhancement',
        'TEMPBONUS:ANYPC|COMBAT|CMD|2+floor(%CHOICE/5)|TYPE=Enhancement',
        'TEMPVALUE:MIN=1|MAX=100|TITLE=Choose the effect caster level',
        'TEMPDESC:Received Slippery aegis. Applies enhancement bonuses to Acrobatics, '
        'Escape Artist and CMD. Its immediate-action escape attempt, duration and '
        'spell-point expenditure remain player-managed. Remove when the aegis ends.',
        'SOURCEPAGE:https://spheresofpower.wikidot.com/protection',
    ]))
    for name, condition in (
            ('Breathless', 'poison or disease'),
            ('Inner Peace', 'fear, emotional, or mind-affecting abilities'),
            ('Resist Transformation', 'polymorph, Enhancement or Alteration sphere effects, '
             'Creation alter effects, transmutation spells, or spell, spell-like, and '
             'supernatural abilities of lycanthropes or creatures with the shapeshifter subtype'),
            ('Deathless', 'Death sphere, death magic, channeled negative energy, or harmful '
             'Life sphere, healing magic, or channeled positive energy'),
            ('Fateless', 'Divination or Fate sphere, divination-school magic, curses, or '
             'spells, spell-like or supernatural abilities originating from hags or outsiders')):
        lines.append('\t'.join([
            'Protection Effect - ' + name + ' - Conditional Saves', 'VISIBLE:NO',
            'TEMPBONUS:ANYPC|SAVE|ALL|4|TYPE=Morale',
            'TEMPDESC:Conditional save modifier only, not the complete ' + name + ' aegis. '
            'Enable ONLY while resolving a saving throw against ' + condition + '. '
            'Disable immediately afterward: PCGen cannot detect the incoming effect. '
            'Having this temporary modifier does not grant new saving throws, immunities, '
            'or permission to cast. Resolve the other aegis benefits at the table.',
            'SOURCEPAGE:https://spheresofpower.wikidot.com/protection',
        ]))
    for name, condition, bonus_type in (
            ('Destructionless', 'ray attacks, evocation-school or Destruction sphere effects, '
             'breath weapons, or attacks and effects originating from elementals', '|TYPE=Morale'),
            ('Eyeless', 'Light or Dark sphere effects, light-based or illusionary attacks '
             '(not saves to disbelieve), gaze attacks, or shadow-descriptor attacks and effects', '|TYPE=Morale'),
            ('Stabilize', 'teleportation, Time or Warp sphere effects, direct telekinesis '
             '(not Bludgeon attacks), time-altering effects, or attacks and abilities '
             'from extraplanar creatures', '|TYPE=Morale'),
            ('Iron Shield', 'environmental damage (not vacuum), nature-resource attacks '
             '(not every electricity attack), Nature or Weather sphere abilities, or '
             'spells, spell-like, and supernatural abilities of fey, magical beasts, or plants', '')):
        lines.append('\t'.join([
            'Protection Effect - ' + name + ' - Conditional Defense', 'VISIBLE:NO',
            'TEMPBONUS:ANYPC|SAVE|ALL|4' + bonus_type,
            'TEMPBONUS:ANYPC|COMBAT|AC|4' + bonus_type,
            'TEMPDESC:Enable ONLY while resolving ' + condition + '. Disable immediately '
            'afterward: PCGen cannot identify the incoming effect. This is a received '
            'conditional defense modifier, not permission to cast or an always-active bonus.',
            'SOURCEPAGE:https://spheresofpower.wikidot.com/protection',
        ]))
    lines.append('\t'.join([
        'Protection Effect - Mettle - Critical Confirmation Only', 'VISIBLE:NO',
        'TEMPBONUS:ANYPC|COMBAT|AC|5+%CHOICE',
        'TEMPVALUE:MIN=1|MAX=100|TITLE=Choose the effect caster level',
        'TEMPDESC:Enable ONLY against a critical hit confirmation roll. Disable immediately '
        'afterward; this untyped AC bonus does not affect ordinary attack rolls. '
        'Use the caster level when the aegis was cast, not the recipient level.',
        'SOURCEPAGE:https://spheresofpower.wikidot.com/protection',
    ]))
    lines.append('\t'.join([
        'Protection Effect - Inner Peace - Situational Skills', 'VISIBLE:NO',
        'TEMPBONUS:ANYPC|SITUATION|Bluff=Conceal Emotions|4|TYPE=Morale',
        'TEMPBONUS:ANYPC|SITUATION|Bluff=Relay Secret Messages|4|TYPE=Morale',
        'TEMPBONUS:ANYPC|SITUATION|Diplomacy=Calm Creatures|4|TYPE=Morale',
        'TEMPDESC:Received Inner Peace skill benefits. Applies only to concealing emotions, '
        'relaying secret messages, or influencing attitudes to make creatures calm. '
        'Does not improve ordinary Bluff or Diplomacy. Remove when the aegis ends; '
        'the saving-throw benefit uses its separate conditional-save toggle.',
        'SOURCEPAGE:https://spheresofpower.wikidot.com/protection',
    ]))
    lines.append('\t'.join([
        'Protection Effect - Guardian - Attacker Penalty', 'VISIBLE:NO',
        'TEMPBONUS:ANYPC|COMBAT|TOHIT|-1-floor(%CHOICE/5)',
        'TEMPVALUE:MIN=1|MAX=100|TITLE=Choose the aegis caster level',
        'TEMPDESC:Apply to the ATTACKER, not the aegis bearer. Enable ONLY for a '
        'hostile attack within 10 feet of the bearer that targets someone else. '
        'Disable immediately afterward. Multiple Guardian aegises do not stack; '
        'do not apply when attacking another Guardian aegis bearer. Range, hostility '
        'and target identity must be checked at the table.',
        'SOURCEPAGE:https://spheresofpower.wikidot.com/protection',
    ]))
    lines.append('\t'.join([
        'Protection Effect - Exclusion - Attacker Penalty', 'VISIBLE:NO',
        'TEMPBONUS:ANYPC|COMBAT|TOHIT|-%CHOICE',
        'TEMPVALUE:MIN=1|MAX=100|TITLE=Choose the ward caster level',
        'TEMPDESC:Apply to the ATTACKER. Enable ONLY for an attack composed of the '
        'excluded material that crosses from outside into the ward. Disable immediately '
        'afterward. This does not penalize attacks wholly inside the ward or grant AC '
        'to its occupants. Material selection, ward boundary, and Strength checks to '
        'enter remain player-managed. Use ward caster level when cast.',
        'SOURCEPAGE:https://spheresofpower.wikidot.com/protection',
    ]))
    lines.append('\t'.join([
        'Protection Effect - Helping Hand - Skill Reroll Only', 'VISIBLE:NO',
        'TEMPBONUS:ANYPC|SKILL|ALL|max(1,floor(%CHOICE/4))|TYPE=Circumstance',
        'TEMPVALUE:MIN=1|MAX=100|TITLE=Choose the succor caster level',
        'TEMPDESC:Enable ONLY for the skill check rerolled using Helping Hand after '
        'sacrificing an aegis. Disable immediately afterward. Take the second result '
        'even if worse. This does not grant a reroll or sacrifice an aegis automatically. '
        'For an ability-check reroll, apply the same bonus at the table instead; '
        'this toggle changes skill checks only.',
        'SOURCEPAGE:https://spheresofpower.wikidot.com/protection',
    ]))
    for energy in ('Acid', 'Cold', 'Electricity', 'Fire', 'Sonic'):
        lines.append('\t'.join([
            'Protection Effect - Energy Resistance - ' + energy, 'VISIBLE:NO',
            'TEMPBONUS:ANYPC|VAR|' + energy + 'ResistanceBonus|10+%CHOICE|TYPE=Resistance',
            'TEMPVALUE:MIN=1|MAX=100|TITLE=Choose the aegis caster level',
            'TEMPDESC:Received Energy Resistance aegis against ' + energy.lower() +
            ' damage only. Use caster level when cast. Does not prevent other side '
            'effects or grant immunity. Does not implement the area ward. Remove '
            'when the aegis ends. Spell points and duration are player-managed.',
            'SOURCEPAGE:https://spheresofpower.wikidot.com/protection',
        ]))
    return '\n'.join(lines) + '\n'