"""Generate PCGen basic-sphere records from the pinned, bounded source manifest.

Rules text is Open Game Content; see data/spheres/catalog-OGL.txt.
Only explicit overrides automate effects. Tactical actions remain sheet rules.
"""
import argparse
import json
import re

from spheres_catalog import inventory
from spheres_catalog_source import ROOT, SNAPSHOTS
from spheres_associated_feats import equivalence_tags

DATA = ROOT / "data/spheres"
LEGACY = {"Admixture", "Searing Blast", "Epicenter", "Gather Energy"}
PACKAGES = {
    "athletics": ("Climb", "Fly", "Leap", "Run", "Swim"),
    "alchemy": ("Formulae", "Poison"),
    "beastmastery": ("Handle Animal", "Ride"),
    "guardian": ("Challenge", "Patrol"),
    "leadership": ("Cohort", "Followers"),
    "nature": ("Air", "Earth", "Fire", "Metal", "Plant", "Water"),
    "tinker": ("Augmentation", "Computation", "Modification", "Transmission", "Transportation"),
    "pilot": ("Naval", "Stellar", "Terrestrial"),
}
EXPAND = {"athletics": "Expanded Training", "alchemy": "Master Chemist",
          "beastmastery": "Extra Beastmastery Package", "guardian": "Expanded Guardian",
          "leadership": "Expanded Leadership", "nature": "Expanded Geomancing",
          "tinker": "Expanded Tinkering", "pilot": "Expanded Piloting"}
SKILLS = {"alchemy": "Craft (Alchemy)", "fencing": "Bluff", "gladiator": "Intimidate",
          "scoundrel": "Sleight of Hand", "scout": "Stealth", "trap": "Craft (Traps)",
          "warleader-sphere": "Diplomacy", "leadership": "Diplomacy",
          "tech": "Craft (Mechanical)", "tinker": "Craft (Mechanical)"}
SKILL_DCS = {"alchemy": "Craft (Alchemy)", "trap": "Craft (Traps)",
             "tech": "Craft (Mechanical)"}


def token(name):
    return re.sub(r"[^A-Za-z0-9]", "", name)


def text(value):
    # DESC parses parentheses as delimiters; published prose includes unmatched ones.
    return " ".join(value.replace("|", "/").replace("%", " percent")
                    .replace("(", "[").replace(")", "]").split())


def category(row):
    return "Spheres Magic Talent" if row["system"] == "power" else "Spheres Combat Talent"


def key(row, talent):
    if row["slug"] == "destruction" and talent["name"] in LEGACY:
        return talent["name"]
    return row["sphere"] + " - " + talent["name"].replace(",", "")


def repeat_limit(talent):
    """Conservative, source-explicit repeatability; no inference from effect scaling."""
    rule = talent["text"]
    phrase = r"(?:take|select|gain) this talent (?:a |an |up to |a total of )?"
    capped = re.search(phrase + r"multiple times, to a maximum of ([2-9]) times", rule, re.I)
    if capped:
        return int(capped[1])
    # An effect unlocked by the second selection is not necessarily a cap.
    if re.search(phrase + r"(?:multiple times|any number of times|as many times|more than once)", rule, re.I):
        return 99
    if re.search(phrase + r"(?:second time|twice|two times)", rule, re.I):
        return 2
    for word, count in (("two",2),("2",2),("three",3),("3",3),("4",4),("5",5)):
        if re.search(phrase + word + r" times", rule, re.I):
            return count
    return 1


def build():
    from spheres_custom_training import build as custom_training
    from spheres_alternative_brew import build as alternative_brew
    from spheres_alternative_brew import skills as brewing_skills
    from spheres_alternative_brew import key as brewing_key
    rows = inventory()
    overrides = json.loads((DATA / "catalog-mechanics.json").read_text())
    categories, packages, output = [], [], {}
    review = []
    for row in rows:
        name, slug, cat = row["sphere"], row["slug"], category(row)
        ident = token(name)
        prefix = "SPHERES_" + ident.upper()
        base = name + " Sphere"
        lines = ["# Generated by tools/spheres_catalog_lst.py; OGC: catalog-OGL.txt",
                 "# " + row["url"]]
        base_tags = [base, "CATEGORY:" + cat, "TYPE:SpheresBaseSphere." + ident,
                     ("PREABILITY:1,CATEGORY=Special Ability,Spheres Casting Core" if row["system"] == "power" else "PREVARGTEQ:SPHERES_COMBAT_TALENTS,1"),
                     "DEFINE:" + prefix + "_TALENTS|0", "BONUS:VAR|" + prefix + "_TALENTS|1"]
        # Repeated selections must not own DEFINEs: removing one selection
        # otherwise undefines the counter while other selections still exist.
        counters = ["DEFINE:" + prefix + "_" + token(t["name"]).upper() + "_COUNT|0"
                    for t in row["talents"] if repeat_limit(t) > 1
                    and not any(tag.startswith("MULT:") for tag in overrides.get(key(row, t), []))]
        base_tags.extend(counters)
        if row["system"] == "power" and slug != "destruction":
            base_tags.extend(["DEFINE:SPHERES_CL_" + ident.upper() + "|SPHERES_CASTER_LEVEL",
                "DEFINE:SPHERES_DC_" + ident.upper() + "|10+floor(SPHERES_CL_" + ident.upper() + "/2)+SPHERES_CASTING_ABILITY"])
        if row["system"] == "might":
            base_tags.extend(["DEFINE:SPHERES_BAB_" + ident.upper() + "|BAB",
                "DEFINE:SPHERES_DC_" + ident.upper() + "|10+floor(" +
                ('SPHERES_ALCHEMY_RANKS' if slug == 'alchemy' else
                 'skillinfo("TOTALRANK","' + SKILL_DCS[slug] + '")' if slug in SKILL_DCS else
                 "SPHERES_BAB_" + ident.upper()) + "/2)+SPHERES_PRACTITIONER_MOD"])
        if slug in SKILLS:
            base_tags.append("BONUS:SKILLRANK|" + SKILLS[slug] + "|min(TL,5*" + prefix + "_TALENTS)|TYPE=SpheresTraining")
            if slug == 'alchemy':
                base_tags[-1] += '|!PREABILITY:1,CATEGORY=Special Ability,Martial Drawback - Alternative-Brew (Heal)'
                base_tags[-1] += '|!PREABILITY:1,CATEGORY=Spheres Alchemy Associated Skill,TYPE.SpheresAlternativeBrew'
                base_tags += [
                    'DEFINE:SPHERES_ALCHEMY_RANKS|0',
                    'BONUS:VAR|SPHERES_ALCHEMY_RANKS|skillinfo("TOTALRANK","Craft (Alchemy)")|!PREABILITY:1,CATEGORY=Special Ability,Martial Drawback - Alternative-Brew (Heal)|!PREABILITY:1,CATEGORY=Spheres Alchemy Associated Skill,TYPE.SpheresAlternativeBrew',
                    'BONUS:VAR|SPHERES_ALCHEMY_RANKS|skillinfo("TOTALRANK","Heal")|PREABILITY:1,CATEGORY=Special Ability,Martial Drawback - Alternative-Brew (Heal)',
                    'BONUS:SKILLRANK|Heal|min(TL,5*SPHERES_ALCHEMY_TALENTS)|TYPE=SpheresTraining|PREABILITY:1,CATEGORY=Special Ability,Martial Drawback - Alternative-Brew (Heal)',
                    'DEFINE:SPHERES_ALCHEMY_FORMULAE|0',
                    'DEFINE:SPHERES_ALCHEMY_PREPARED_FORMULAE|max(1,floor(SPHERES_ALCHEMY_RANKS/2))+SPHERES_ALCHEMY_FORMULAE',
                    'DEFINE:SPHERES_ALCHEMY_BATCH|1+floor(SPHERES_ALCHEMY_RANKS/4)',
                    'DEFINE:SPHERES_ALCHEMY_POISON_ROUNDS|1+floor(SPHERES_ALCHEMY_RANKS/4)']
                # skillinfo returns zero for skills absent from the character's
                # display list even when BONUS:SKILLRANK grants ranks. Preserve
                # the known training minimum without adding it twice.
                base_tags.extend('BONUS:VAR|SPHERES_ALCHEMY_RANKS|max(min(TL,5*SPHERES_ALCHEMY_TALENTS),skillinfo("TOTALRANK","' + skill + '"))|PREABILITY:1,CATEGORY=Spheres Alchemy Associated Skill,' + brewing_key(skill)
                                 for skill in brewing_skills())
                categories.append('\t'.join([
                    'ABILITYCATEGORY:Spheres Alchemy Bonus Formula', 'CATEGORY:' + cat,
                    'TYPE:AlchemyFormula', 'EDITABLE:YES', 'EDITPOOL:NO',
                    'FRACTIONALPOOL:NO', 'VISIBLE:QUALIFY', 'POOL:0',
                    'PLURAL:Alchemy Free Formula', 'DISPLAYLOCATION:Spheres']))
        if slug == "equipment-sphere":
            base_tags.append("BONUS:ABILITYPOOL|Spheres Equipment Bonus Talent|1")
            categories.append("\t".join(["ABILITYCATEGORY:Spheres Equipment Bonus Talent", "CATEGORY:" + cat,
                "TYPE:EquipmentTalent", "EDITABLE:YES", "EDITPOOL:NO", "FRACTIONALPOOL:NO", "VISIBLE:QUALIFY",
                "POOL:0", "PLURAL:Equipment Free Talent", "DISPLAYLOCATION:Spheres"]))
        if slug == "tech":
            base_tags.append("BONUS:ABILITYPOOL|Spheres Tech Bonus Gadget|1")
            base_tags.append("DEFINE:SPHERES_TECH_RANGEAMPLIFIER_COUNT|0")
            base_tags.append("DEFINE:SPHERES_TECH_DRONE_AI_COUNT|0")
            categories.append("\t".join(["ABILITYCATEGORY:Spheres Tech Bonus Gadget", "CATEGORY:" + cat,
                "TYPE:TechGadget", "EDITABLE:YES", "EDITPOOL:NO", "FRACTIONALPOOL:NO", "VISIBLE:QUALIFY",
                "POOL:0", "PLURAL:Tech Free Gadget", "DISPLAYLOCATION:Spheres"]))
        if slug in PACKAGES:
            package_cat = "Spheres " + name + " Package"
            var = prefix + "_PACKAGES"
            base_tags.extend(["DEFINE:" + var + "|0", "BONUS:VAR|" + var + "|1"])
            categories.append("\t".join(["ABILITYCATEGORY:" + package_cat, "CATEGORY:" + package_cat,
                "EDITABLE:YES", "EDITPOOL:NO", "FRACTIONALPOOL:NO", "VISIBLE:QUALIFY", "POOL:" + var,
                "PLURAL:" + name + " Packages", "DISPLAYLOCATION:Spheres"]))
            source = json.loads((SNAPSHOTS / (slug + ".json")).read_text())["sections"]
            for choice in PACKAGES[slug]:
                matching = [s for s in source[:60] if s["heading"].lower() == choice.lower()]
                desc = matching[0]["text"] if matching else "See the base sphere's " + choice + " package rules."
                package_tags = [name + " Package - " + choice, "CATEGORY:" + package_cat,
                    "TYPE:" + ident + "Package." + token(choice), "PREABILITY:1,CATEGORY=" + cat + "," + base,
                    "DESC:" + text(desc)]
                skill = ({"Climb":"Climb", "Fly":"Fly", "Leap":"Acrobatics", "Run":"Acrobatics", "Swim":"Swim"}.get(choice)
                         if slug == "athletics" else choice if slug == "beastmastery" else None)
                if skill:
                    package_tags.append("BONUS:SKILLRANK|" + skill + "|min(TL,5*" + prefix + "_TALENTS)|TYPE=SpheresTraining")
                    if slug == 'athletics':
                        package_tags[-1] += '|!PREABILITY:1,CATEGORY=Special Ability,Martial Drawback - Driver'
                if slug == 'alchemy' and choice == 'Formulae':
                    package_tags.append('BONUS:ABILITYPOOL|Spheres Alchemy Bonus Formula|1')
                packages.append("\t".join(package_tags))
        base_tags += [re.sub(r"\bBAB\b", "SPHERES_BAB_" + ident.upper(), tag)
                      if row["system"] == "might" else tag for tag in overrides.get(base, [])]
        base_tags += ["DESC:" + text(row["base"]) + " Automation is partial; consult docs/sphere-catalog.md. Unautomated rules must be applied manually.",
                      "SOURCEPAGE:" + row["url"]]
        base_tags += equivalence_tags(base)
        if slug != "destruction":
            lines.append("\t".join(base_tags))
        elif counters:
            lines.append("\t".join(["CATEGORY=" + cat + "|" + base + ".MOD", *counters]))
        for talent in row["talents"]:
            name_key = key(row, talent)
            if slug == "destruction" and talent["name"] in LEGACY:
                continue
            tags = [name_key, "CATEGORY:" + cat, "TYPE:SpheresBasicTalent." + ident,
                    "PREABILITY:1,CATEGORY=" + cat + "," + base,
                    "BONUS:VAR|" + prefix + "_TALENTS|1"]
            if name_key == 'Scout - Somnambulance':
                tags[3] = ('PREMULT:1,[PREABILITY:1,CATEGORY=Spheres Combat Talent,Scout Sphere],'
                           '[PREABILITY:1,CATEGORY=Special Ability,Elf ~ Spheres Dreamless Sleep,'
                           'Half-Elf ~ Spheres Dreamless Sleep]')
            if slug == "equipment-sphere":
                tags[2] += ".EquipmentTalent"
            if slug == 'alchemy' and '(formulae)' in talent['heading'].lower():
                tags[2] += '.AlchemyFormula'
                tags.append('BONUS:VAR|SPHERES_ALCHEMY_FORMULAE|1')
            if slug == "tech" and re.search(r"\([^)]*\bgadget\b[^)]*\)", talent["heading"]):
                tags[2] += ".TechGadget"
                tags.append("BONUS:VAR|SPHERES_TECH_GADGET_TALENTS|1")
            limit = repeat_limit(talent)
            if name_key in overrides and any(t.startswith("MULT:") for t in overrides[name_key]):
                limit = 1
            if limit > 1:
                counter = prefix + "_" + token(talent["name"]).upper() + "_COUNT"
                tags += ["MULT:YES", "STACK:YES", "CHOOSE:NOCHOICE",
                         "BONUS:VAR|" + counter + "|1"]
                if limit < 99:
                    tags += ["PREVARLT:" + counter + "," + str(limit)]
            if slug in PACKAGES:
                inside = " ".join(re.findall(r"\(([^)]*)\)", talent["heading"])).lower()
                matches = [p for p in PACKAGES[slug] if p.lower() in re.split(r", | or ", inside)]
                if slug == 'alchemy' and talent['group'] == 'Toxin Talents':
                    matches = ['Poison']
                if matches:
                    tags.append("PREABILITY:1,CATEGORY=Spheres " + name + " Package," + ",".join(name + " Package - " + p for p in matches))
                if talent["name"] == EXPAND[slug]:
                    tags.append("BONUS:VAR|" + prefix + "_PACKAGES|" + ("2" if slug in ("tinker", "athletics") else "1"))
                    tags.append("PREVARLT:" + prefix + "_PACKAGES," + str(len(PACKAGES[slug])))
            match = re.search(r"^Prerequisites?: Caster level (\d+)", talent["text"])
            if match:
                tags.append("PREVARGTEQ:SPHERES_CASTER_LEVEL," + match[1])
            tags += overrides.get(name_key, [])
            tags += equivalence_tags(name_key)
            if name_key == 'Equipment - Versatile Fighter':
                tags.append('BONUS:ABILITYPOOL|Spheres Versatile Fighter Stance|1')
            if name_key == 'Equipment - Custom Training':
                tags.append('BONUS:ABILITYPOOL|Spheres Custom Training Weapon|5')
            tags += ["DESC:" + text(talent["text"]) + " Automation is partial; consult docs/sphere-catalog.md. Unautomated rules must be applied manually.",
                     "SOURCEPAGE:" + talent["url"]]
            lines.append("\t".join(tags))
            review.append({"key": name_key, "sphere": name, "repeat_limit": limit,
                           "mechanics": overrides.get(name_key, []),
                           "prerequisites": [t for t in tags if t.startswith("PRE")]})
        output[f"spheres_{row['system']}_{slug}.lst"] = "\n".join(lines) + "\n"
    stance_category = 'Spheres Versatile Fighter Stance'
    categories.append('\t'.join([
        'ABILITYCATEGORY:' + stance_category, 'CATEGORY:' + stance_category,
        'EDITABLE:YES', 'EDITPOOL:NO', 'FRACTIONALPOOL:NO', 'VISIBLE:QUALIFY',
        'POOL:0', 'PLURAL:Active Versatile Fighter stance', 'DISPLAYLOCATION:Spheres']))
    for stance, feats in (('Offensive Style', ('Deadly Aim', 'Power Attack')),
                          ('Defensive Style', ('Combat Expertise',)),
                          ('Recovery Style', ('Heroic Resolve',))):
        requirement = 'PREABILITY:1,CATEGORY=Spheres Combat Talent,Equipment - Versatile Fighter'
        packages.append('\t'.join([
            'Versatile Fighter - ' + stance, 'CATEGORY:' + stance_category, requirement,
            # Conditional grants prevent a retained but invalid stance record
            # from continuing to supply feat benefits after the talent is removed.
            'ABILITY:FEAT|AUTOMATIC|' + '|'.join(feats) + '|' + requirement,
            'DESC:Active ' + stance + '. Select only while this stance is active; '
            'remove when leaving it. Use the existing feat attack options to apply '
            'their bonuses and penalties. Resolve stance entry, duration, and '
            'on-hit riders at the table. Other simultaneous stances remain manual.',
            'SOURCEPAGE:https://spheresofpower.wikidot.com/equipment-sphere']))
    training_category, training_choices = custom_training()
    categories.append(training_category)
    packages.extend(training_choices)
    brew_category, brew_choices = alternative_brew()
    categories.append(brew_category)
    packages.extend(brew_choices)
    output["spheres_categories_catalog.lst"] = "\n".join(categories) + "\n"
    output["spheres_catalog_packages.lst"] = "\n".join(packages) + "\n"
    from spheres_enhancement_effects import templates
    output["spheres_enhancement_effects.lst"] = templates()
    from spheres_protection_effects import templates as protection_templates
    output["spheres_protection_effects.lst"] = protection_templates()
    from spheres_fate_effects import templates as fate_templates
    output["spheres_fate_effects.lst"] = fate_templates()
    from spheres_divination_effects import templates as divination_templates
    output["spheres_divination_effects.lst"] = divination_templates()
    from spheres_time_effects import templates as time_templates
    output["spheres_time_effects.lst"] = time_templates()
    return output, review


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    files, review = build()
    if args.write:
        for name, content in files.items():
            (DATA / name).write_text(content, encoding="utf-8")
        (DATA / "catalog-review.json").write_text(json.dumps(review, indent=2) + "\n")
        legal = json.loads((SNAPSHOTS / "legal-start.json").read_text())["sections"][0]["text"]
        (DATA / "catalog-OGL.txt").write_text("Sphere rules in the generated catalog are Open Game Content.\nSource: https://spheresofpower.wikidot.com/legal:start\n\n" + legal + "\n")
    else:
        for name, content in files.items():
            if (DATA / name).read_text() != content:
                raise ValueError("Generated file differs: " + name)
    print(f"PASS: {len(files)} deterministic catalog files; {len(review)} additional talents")


if __name__ == "__main__":
    main()