"""Received Enhancement effects using PCGen's native temporary bonuses."""
from spheres import ROOT, DATA, records


def skills():
    paths = (ROOT / 'vendor/upstream/pcgen-6.08.00RC10/data/pathfinder/paizo/roleplaying_game/core_rulebook/cr_skills.lst',
             DATA / 'spheres_skills.lst')
    return sorted({row.split('\t')[0] for path in paths for row in records(path)
                   if '.MOD\t' not in row and not row.startswith('SOURCE')})


def effect_key(talent, target):
    return 'Enhancement Effect - ' + talent + ' - ' + target


def templates():
    lines = ["# Generated by tools/spheres_catalog_lst.py; OGC: catalog-OGL.txt"]
    for talent, stats in (("Physical Enhancement", ("STR", "DEX", "CON")),
                          ("Mental Enhancement", ("INT", "WIS", "CHA"))):
        for stat in stats:
            lines.append('\t'.join([
                effect_key(talent, stat),
                'VISIBLE:NO',
                'TEMPBONUS:ANYPC|STAT|' + stat + '|2+2*floor(%CHOICE/7)|TYPE=Enhancement',
                'TEMPVALUE:MIN=1|MAX=100|TITLE=Choose the effect caster level',
                'TEMPDESC:Received ' + talent + ' affecting ' + stat + '. Enter the caster level '
                'when cast, not the recipient level. Apply only while the enhancement is active. '
                'One ability score per casting; Dual Enhancement permits two for an additional '
                'spell point. Duration, concentration, targeting, and spell-point expenditure '
                'are tracked at the table. This does not grant the talent or permission to cast.',
                'SOURCEPAGE:https://spheresofpower.wikidot.com/enhancement',
            ]))
    for target, bonus in [(save, 'SAVE|' + save + '|2+floor(%CHOICE/5)')
                          for save in ('Fortitude', 'Reflex', 'Will')] + [
                          (skill, 'SKILL|' + skill + '|5+floor(%CHOICE/4)|TYPE=Enhancement')
                          for skill in skills()]:
        talent = 'Staunch Resistance' if bonus.startswith('SAVE|') else 'Enhance Focus'
        lines.append('\t'.join([
            effect_key(talent, target), 'VISIBLE:NO',
            'TEMPBONUS:ANYPC|' + bonus,
            'TEMPVALUE:MIN=1|MAX=100|TITLE=Choose the effect caster level',
            'TEMPDESC:Received ' + talent + ' affecting only ' + target + '. Enter the caster '
            'level when cast. Remove when the effect expires. This neither grants the talent '
            'nor spends spell points. One selected target statistic per casting; Dual '
            'Enhancement permits two for an additional spell point.',
            'SOURCEPAGE:https://spheresofpower.wikidot.com/enhancement',
        ]))
    lines.append('\t'.join([
        'Enhancement Effect - Superior Reflexes', 'VISIBLE:NO',
        'TEMPBONUS:ANYPC|COMBAT|INITIATIVE|1+floor((%CHOICE-1)/4)',
        'TEMPBONUS:ANYPC|VAR|SPHERES_RECEIVED_SUPERIOR_REFLEXES_AOO|1+floor((%CHOICE-1)/4)',
        'TEMPVALUE:MIN=1|MAX=100|TITLE=Choose the effect caster level',
        'TEMPDESC:Received Superior Reflexes. Initiative and additional attacks of opportunity '
        'increase by 1 at caster levels 5, 9, 13, and every 4 thereafter. Allows attacks of '
        'opportunity while flat-footed. Track their expenditure at the table; this does not '
        'grant Combat Reflexes. Remove when the enhancement expires.',
        'SOURCEPAGE:https://spheresofpower.wikidot.com/enhancement',
    ]))
    lines.append('\t'.join([
        'Enhancement Effect - Spectral Enhancement - Conditional Saves', 'VISIBLE:NO',
        'TEMPBONUS:ANYPC|SAVE|ALL|2+floor(%CHOICE/5)|TYPE=Circumstance',
        'TEMPVALUE:MIN=1|MAX=100|TITLE=Choose the effect caster level',
        'TEMPDESC:Enable ONLY for saves against possession or negative energy effects '
        'while wearing armor granted ghost touch by Spectral Enhancement with the '
        'additional spell point paid. Disable immediately afterward. This does not '
        'grant ghost touch, negative energy resistance, or any benefit to an enhanced '
        'weapon. Enter the effect caster level, not the wearer level.',
        'SOURCEPAGE:https://spheresofpower.wikidot.com/enhancement',
    ]))
    for movement in ('Walk', 'Climb', 'Swim', 'Fly', 'Burrow'):
        lines.append('\t'.join([
            effect_key('Alter Movement', movement), 'VISIBLE:NO',
            'TEMPBONUS:ANYPC|MOVEADD|TYPE.' + movement + '|10+10*floor(%CHOICE/5)|TYPE=Enhancement',
            'TEMPVALUE:MIN=1|MAX=100|TITLE=Choose the effect caster level',
            'TEMPDESC:Received Alter Movement speed increase for an existing ' + movement +
            ' speed only. Does not grant a new movement mode. Apply the separate '
            'conditional skill modifier only while using this speed. Remove when '
            'the effect ends. This does not implement the decreasing-speed option.',
            'SOURCEPAGE:https://spheresofpower.wikidot.com/enhancement',
        ]))
    for weight, penalty in (('Half Weight', 2), ('Weightless or Floating', 4)):
        lines.append('\t'.join([
            effect_key('Lighten', weight + ' - Conditional CMD'), 'VISIBLE:NO',
            'TEMPBONUS:ANYPC|COMBAT|CMD|-' + str(penalty),
            'TEMPDESC:Enable ONLY while resolving bull rush, drag, or reposition '
            'against a creature affected by Lighten (' + weight.lower() + '). '
            'Disable immediately afterward. Choose only one Lighten weight state. '
            'Does not change body weight, armor, movement, or ordinary CMD.',
            'SOURCEPAGE:https://spheresofpower.wikidot.com/enhancement',
        ]))
    lines.append('\t'.join([
        'Enhancement Effect - Lighten - Levitating Attack', 'VISIBLE:NO',
        'TEMPBONUS:ANYPC|COMBAT|TOHIT|-%CHOICE',
        'TEMPVALUE:MIN=1|MAX=5|TITLE=Choose attack penalty since last stabilization (maximum 5)',
        'TEMPDESC:For weapon attacks while levitating from Lighten only. Choose 1 '
        'for the first attack, 2 for the second, up to 5. Replace this modifier '
        'as the penalty advances. A full-round action stabilizing resets the next '
        'attack to 1. Disable for nonweapon attacks and remove on landing or '
        'expiration. Does not automatically count attacks or spend actions.',
        'SOURCEPAGE:https://spheresofpower.wikidot.com/enhancement',
    ]))
    lines.append('\t'.join([
        'Enhancement Effect - Alter Movement - Conditional Skills', 'VISIBLE:NO',
        'TEMPBONUS:ANYPC|SKILL|Acrobatics,Climb,Fly,Swim|2+2*floor(%CHOICE/5)|TYPE=Enhancement',
        'TEMPVALUE:MIN=1|MAX=100|TITLE=Choose the effect caster level',
        'TEMPDESC:Enable ONLY for a check while using the movement speed increased '
        'by Alter Movement. Disable immediately afterward; other movement modes '
        'and checks do not benefit. Use the caster level when cast.',
        'SOURCEPAGE:https://spheresofpower.wikidot.com/enhancement',
    ]))
    lines.append('\t'.join([
        'Enhancement Effect - Cripple', 'VISIBLE:NO',
        'TEMPBONUS:ANYPC|COMBAT|TOHIT,INITIATIVE|-2-floor(%CHOICE/5)',
        'TEMPBONUS:ANYPC|SAVE|ALL|-2-floor(%CHOICE/5)',
        'TEMPBONUS:ANYPC|SKILL|ALL|-2-floor(%CHOICE/5)',
        'TEMPVALUE:MIN=1|MAX=100|TITLE=Choose the effect caster level',
        'TEMPDESC:Received Cripple. Applies penalties to attack rolls, saves, skills '
        'and initiative (a Dexterity check). Apply the same penalty to other ability '
        'checks at the table; ability scores themselves are unchanged. Enter caster '
        'level when cast. Target legality, saving throw, duration and spell points '
        'remain player-managed. Remove when the effect ends.',
        'SOURCEPAGE:https://spheresofpower.wikidot.com/enhancement',
    ]))
    return '\n'.join(lines) + '\n'