"""Source-backed prestige adapters; independent casting is not aligned-class advancement."""
import argparse
import json

from spheres import DATA
from spheres_catalog_source import SNAPSHOTS


def tempestarii():
    source = json.loads((SNAPSHOTS / 'tempestarii.json').read_text())
    sections = {r['heading']: r for r in source['sections']}
    features = {1: ('Rapid Weather',), 2: ('Ship Smasher',), 3: ('Grand Weather',),
                4: ('Ship Killer',), 5: ('Deadly Weather', 'Instant Weather')}
    classes = ['# Generated by tools/spheres_prestige.py from pinned Tempestarii rules.',
               '\t'.join(['CLASS:Tempestarii', 'HD:6', 'TYPE:Prestige.PC', 'MAXLEVEL:5',
                          'STARTSKILLPTS:4',
                          'CSKILL:Fly|Intimidate|Knowledge (Geography)|Knowledge (Nature)|Perception|TYPE=Profession|Spellcraft|Survival',
                          'PREVARGTEQ:SPHERES_CL_WEATHER,5',
                          'PREABILITY:1,CATEGORY=Spheres Magic Talent,Weather Sphere',
                          'PRESKILL:1,Knowledge (Nature)=5',
                          'BONUS:COMBAT|BASEAB|floor(CL/2)|TYPE=Base.REPLACE',
                          'BONUS:SAVE|BASE.Fortitude,BASE.Reflex|floor((CL+1)/3)',
                          'BONUS:SAVE|BASE.Will|floor((CL+1)/2)',
                          'DEFINE:SPHERES_TEMPESTARII_LEVEL|0',
                          'BONUS:VAR|SPHERES_TEMPESTARII_LEVEL|CL',
                          'BONUS:VAR|SPHERES_CASTER_LEVEL,SPHERES_MAGIC_SKILL_BONUS,SPHERES_SPELL_POOL_LEVELS|CL',
                          'SOURCEPAGE:' + source['url']])]
    abilities = ['# Generated by tools/spheres_prestige.py; conditional weather effects remain sheet rules.']
    for level, names in features.items():
        tags = [str(level), 'BONUS:VAR|SPHERES_MAGIC_TALENTS|1']
        if level == 1:
            tags.append('ABILITY:Special Ability|AUTOMATIC|Spheres Casting Core')
        for name in names:
            key = 'Tempestarii ' + name
            tags.append('ABILITY:Special Ability|AUTOMATIC|' + key)
            row = sections[name]
            body = row['text'].split('\n| Spheres of Power')[0]
            body = ' '.join(body.replace('|', '/').replace('%', ' percent').split())
            ability = [key, 'CATEGORY:Special Ability', 'TYPE:TempestariiClassFeature',
                       'DESC:' + body, 'SOURCEPAGE:' + source['url'] + '#' + row['anchor']]
            if name == 'Rapid Weather':
                ability += ['DEFINE:SPHERES_TEMPESTARII_WEATHER_STEPS|0',
                            'BONUS:VAR|SPHERES_TEMPESTARII_WEATHER_STEPS|1+SPHERES_TEMPESTARII_LEVEL']
            abilities.append('\t'.join(ability))
        classes.append('\t'.join(tags))
    return {'spheres_tempestarii_class.lst': '\n'.join(classes) + '\n',
            'spheres_tempestarii_features.lst': '\n'.join(abilities) + '\n'}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    for name, content in tempestarii().items():
        path = DATA / name
        if args.write:
            path.write_text(content)
        elif path.read_text() != content:
            raise ValueError('Stale prestige data: ' + name)
    print('PASS: Tempestarii generated progression')


if __name__ == '__main__':
    main()