"""Received Divination modifiers; sensing, casting and discharge remain explicit."""


def templates():
    lines = ['# Generated by tools/spheres_catalog_lst.py; OGC: catalog-OGL.txt']
    effects = [
        ('Discern Individual - Monster Lore', [
            'SKILL|Knowledge (Arcana),Knowledge (Dungeoneering),Knowledge (Local),Knowledge (Nature),Knowledge (Planes),Knowledge (Religion)|max(1,floor(%CHOICE/2))|TYPE=Insight'],
         'Enable ONLY for monster lore checks while Discern Individual is active. '
         'Disable for other Knowledge checks. Monster lore may be attempted '
         'untrained under this sense; this modifier does not grant skill ranks '
         'or enable unrelated untrained Knowledge checks. Resolve untrained '
         'eligibility at the table.'),
        ('Ghost Sight - Invisible or Ethereal Target', ['SKILL|Perception|%CHOICE'],
         'Enable ONLY for Perception checks to notice an invisible or ethereal '
         'creature. Disable for other checks. Revealing its outline and tracking '
         'line of sight, concealment and attack consequences remain player-managed.'),
        ('Unhooded Sight - Disbelieve Illusion', [
            'SAVE|Will|max(1,floor(%CHOICE/2))',
            'SKILL|Perception|max(1,floor(%CHOICE/2))',
            'VAR|SPHERES_MAGIC_SKILL_BONUS|max(1,floor(%CHOICE/2))'],
         'Enable ONLY while resolving a Will save, Perception check or magic '
         'skill check to disbelieve an illusion. Disable immediately afterward. '
         'Other saving throws, Perception checks and magic skill checks do not '
         'benefit; this does not automatically reveal illusions.'),
        ('Divine Capability - Assessed Target', ['SKILL|ALL|floor(%CHOICE/2)|TYPE=Circumstance'],
         'Enable ONLY for a skill check to assess proficiency or identify feats, '
         'talents or class features against a creature successfully divined '
         'with Divine Capability. Disable immediately after that check. Other '
         'skill checks and other targets do not benefit. The target Will save '
         'and assessment results remain player-managed.'),
        ('Nature Sense', ['SKILL|Knowledge (Nature),Survival|1+floor(%CHOICE/5)'],
         'Received Nature Sense. The untyped bonus stacks with same-named class '
         'features. Rerolling a failed Survival check against natural hazards or '
         'getting lost and dismissing the sense remain player-managed.'),
        ('Prescience', ['COMBAT|TOHIT|1+floor(%CHOICE/10)|TYPE=Insight'],
         'Received current Prescience sense. Adds to attack rolls only; does not '
         'grant a separate combat maneuver bonus. Remove on dismissal or expiration.'),
        ('Prescience - Dismissed Attack', ['COMBAT|TOHIT|10+floor(%CHOICE/2)|TYPE=Insight'],
         'Enable ONLY for the attack chosen when dismissing Prescience. Remove '
         'the ongoing sense separately and disable this modifier immediately '
         'after the roll. Does not apply to subsequent attacks.'),
        ('Prescience - Dismissed Maneuver', ['COMBAT|CMB|10+floor(%CHOICE/2)|TYPE=Insight'],
         'Enable ONLY for the combat maneuver chosen when dismissing Prescience. '
         'Remove the ongoing sense separately and disable immediately after '
         'the roll. Does not grant CMD or ordinary attack bonuses.'),
        ('Foreshadow', ['SAVE|Reflex|2+floor(%CHOICE/10)',
                       'COMBAT|INITIATIVE|2+floor(%CHOICE/10)'],
         'Received Foreshadow numeric benefits. Surprise-round and first-turn '
         'flat-footed protection is player-managed; this does not grant Uncanny '
         'Dodge or immunity to all causes of flat-footed. Apply its separate '
         'Dodge AC effect only when eligible for dodge bonuses.'),
        ('Foreshadow - Dodge AC', ['COMBAT|AC|1+floor(%CHOICE/10)|TYPE=Dodge'],
         'Received Foreshadow dodge bonus only. Disable when denied dodge '
         'bonuses, without removing its separate Reflex and initiative effect.'),
    ]
    for name, bonuses, description in effects:
        lines.append('\t'.join([
            'Divination Effect - ' + name, 'VISIBLE:NO',
            *['TEMPBONUS:ANYPC|' + bonus for bonus in bonuses],
            'TEMPVALUE:MIN=1|MAX=100|TITLE=Choose the sense caster level',
            'TEMPDESC:' + description + ' Enter caster level when cast, not '
            'recipient level. Duration, spell points and eligibility remain '
            'player-managed. This does not grant the source talent.',
            'SOURCEPAGE:https://spheresofpower.wikidot.com/divination',
        ]))
    lines.append('\t'.join([
        'Divination Effect - Sensory Overload - Mindless Target', 'VISIBLE:NO',
        'TEMPBONUS:ANYPC|SAVE|Fortitude,Will|-2',
        'TEMPDESC:Enable ONLY for a mindless target resolving the Fortitude or '
        'Will save against Sensory Overload. Disable immediately afterward; '
        'unrelated saving throws do not suffer this penalty. Does not make the '
        'recipient mindless. Nonlethal damage, flat-footed state, action '
        'restrictions, concentration and ending the effect remain player-managed.',
        'SOURCEPAGE:https://spheresofpower.wikidot.com/divination',
    ]))
    for target, bonus in (
            ('Attack', 'COMBAT|TOHIT'), ('Skill', 'SKILL|ALL'),
            ('Save', 'SAVE|ALL'), ('Initiative', 'COMBAT|INITIATIVE'),
            ('Maneuver', 'COMBAT|CMB')):
        lines.append('\t'.join([
            'Divination Effect - Divine Future - ' + target, 'VISIBLE:NO',
            'TEMPBONUS:ANYPC|' + bonus + '|%CHOICE|TYPE=Insight',
            'TEMPVALUE:MIN=1|MAX=100|TITLE=Enter rolled d4 plus floor(caster level/5)',
            'TEMPDESC:Enable ONLY for the chosen ' + target.lower() +
            ' roll when spending Divine Future. Enter the rolled d4 plus '
            'floor(caster level/5), not caster level. Disable immediately after '
            'the roll. Initiative represents Dexterity ability checks only; '
            'other ability checks remain table-resolved. Does not roll dice, '
            'track available uses, refresh divinations or spend the immediate '
            'action to grant this benefit to an ally who sees and hears you.',
            'SOURCEPAGE:https://spheresofpower.wikidot.com/divination',
        ]))
    lines.append('\t'.join([
        'Divination State - Active Senses', 'VISIBLE:NO',
        'TEMPBONUS:ANYPC|VAR|SPHERES_ACTIVE_DIVINATION_SENSES|%CHOICE',
        'TEMPVALUE:MIN=0|MAX=100|TITLE=Enter number of currently active Divination senses',
        'TEMPDESC:Player-maintained count for owned Precogniscent feats. Enter '
        'active senses, not known talents or caster level. Replace this single '
        'state whenever a sense starts, expires or is dismissed. This record '
        'grants no sense or feat. Feats enforce their own Hit-Dice caps. '
        'Immediate actions, spell points, rerolls and critical-hit conversion '
        'remain player-managed.',
        'SOURCEPAGE:https://spheresofpower.wikidot.com/divination',
    ]))
    for target, bonus, cap in (
            ('Distance Perception', 'SKILL|Perception', 'caster level'),
            ('Ranged Attack Penalties', 'COMBAT|TOHIT', 'floor(caster level/2)')):
        lines.append('\t'.join([
            "Divination Effect - Sniper's Eye - " + target, 'VISIBLE:NO',
            'TEMPBONUS:ANYPC|' + bonus + '|%CHOICE',
            'TEMPVALUE:MIN=0|MAX=100|TITLE=Enter eligible penalty reduction, not caster level',
            "TEMPDESC:For Sniper's Eye only. Enter the lesser of the eligible "
            'penalty magnitude and ' + cap + '. Keep the original penalty active '
            'or included in the check DC. This only offsets penalties and must '
            'never produce a net bonus. Perception applies only to distance-based '
            'DC increases; attack applies only to environmental and range-increment '
            'penalties on ranged attacks. Disable for other checks or attacks. '
            'Recalculate when range or conditions change.',
            'SOURCEPAGE:https://spheresofpower.wikidot.com/divination',
        ]))
    return '\n'.join(lines) + '\n'