"""Compile reviewed general casting options from the pinned Ultimate section.

Published action restrictions remain rules text; persistent grants use PCGen.
Variable-credit systems are deliberately excluded until their choices are modeled.
"""
import argparse
import json
import re

from spheres import DATA
from spheres_catalog_source import SNAPSHOTS

OUTPUT = DATA / 'spheres_casting_options.lst'
LEGACY = {'Verbal Casting', 'Somatic Casting', 'Focus Casting', 'Magical Signs',
          'Prepared Caster', 'Draining Casting', 'Addictive Casting', 'Area Bound',
          'Bonded Casting', 'Charged Spells', 'Mental Focus', 'Terrain Casting',
          'Unsettling Casting', 'Vampiric Casting', 'Extended Casting'}
DEFERRED = {'Card Casting', 'Oathbound Casting', 'Singular Pool', 'Catastrophic Failure'}
DOUBLE = {'Diagram Magic', 'Dedicated Wright', 'Narcoleptic Casting', 'Planebound Magic', 'Unstable Storage'}
REPEATED = {'Bonded Casting', 'Consciousness Linked', 'Coy Caster', 'Skilled Casting',
            'Substantial Magic', 'Unreliable Replenishment', 'Vampiric Casting'}
CONFLICTS = (
    ('Age of Reason', 'Clarke Compliance'),
    ('Bonded Casting', 'Center Of Power'), ('Bonded Casting', 'Focus Casting'),
    ('Bonded Casting', 'Galvanized'), ('Bonded Casting', 'Spell Stand-In'),
    ('Charged Spells', 'Diagram Magic'), ('Charged Spells', 'Prepared Caster'),
    ('Dreamlost Casting', 'Narcoleptic Casting'),
    ('Focus Casting', 'Center Of Power'), ('Focus Casting', 'Galvanized'),
    ('Galvanized', 'Center Of Power'), ('Magical Signs', 'Witchmarked'),
    ('Madness Mantra', 'Emotional Casting'),
    ('Madness Mantra - Variant', 'Emotional Casting'),
    ('Spell Tokens', 'Extended Casting'),
)
TACTICAL_BOONS = {'Alien Source', 'Atmoturgy', 'Confluent Casting', 'Deathful Magic',
                  'Draw Magic', 'Empowered Abilities', 'Overcharge', 'Overconsumption',
                  'Overwhelming Power', 'Sanguine Empowerment', 'Unbound Magic',
                  'Virtuoso', 'Wild Surge'}


def name(heading):
    return re.sub(r'\s*\[[^]]+\]', '', heading).strip().replace(',', ' -')


def sections(heading):
    source = json.loads((SNAPSHOTS / 'casting-traditions.json').read_text())
    rows = source['sections']
    start = next(i for i, row in enumerate(rows) if row['heading'] == heading)
    end = next(i for i in range(start + 1, len(rows))
               if rows[i]['level'] <= rows[start]['level'])
    result = {}
    for row in rows[start + 1:end]:
        if row['level'] != 4:
            continue
        key = name(row['heading'])
        if key in result:
            raise ValueError('Duplicate Ultimate tradition option: ' + key)
        result[key] = row
    return result


def conflicts(key):
    return ['!PREABILITY:1,CATEGORY=Custom Casting Drawback,Tradition - ' + other
            for pair in CONFLICTS if key in pair for other in pair if other != key]


def description(row):
    return ' '.join(row['text'].replace('|', '/').replace('%', ' percent')
                    .replace('(', '[').replace(')', ']').split())


def build():
    rows = ['# Generated by tools/spheres_traditions.py from pinned Ultimate rules.']
    drawbacks = sections('General Drawbacks')
    for key, row in drawbacks.items():
        if key in LEGACY | DEFERRED:
            continue
        weight = 2 if key in DOUBLE else 1
        grants = {'Benefactor': ['ABILITY:Spheres Magic Talent|AUTOMATIC|Mana Sphere|Mana - Gift Of Knowledge'],
                  'Spell Stand-In': ['ABILITY:Spheres Magic Talent|AUTOMATIC|Conjuration Sphere|Conjuration - Spell Conduit',
                                    'ABILITY:FEAT|AUTOMATIC|Spell Channel']}
        tags = ['Tradition - ' + key, 'CATEGORY:Custom Casting Drawback',
                'COST:' + str(weight),
                'PREABILITY:1,CATEGORY=Custom Casting Tradition,Custom Casting Tradition',
                *conflicts(key),
                'BONUS:ABILITYPOOL|Custom Casting Boon|' + str(weight),
                'BONUS:VAR|SPHERES_TRADITION_DRAWBACKS|' + str(weight),
                *grants.get(key, []),
                'DESC:' + description(row) + ' Resolve casting restrictions and situational effects at the table.',
                'SOURCEPAGE:https://spheresofpower.wikidot.com/casting-traditions#' + row['anchor']]
        rows.append('\t'.join(tags))
    for key in sorted(REPEATED):
        row = drawbacks[key]
        rows.append('\t'.join([
            'Tradition - ' + key + ' Second Selection', 'CATEGORY:Custom Casting Drawback',
            'PREABILITY:1,CATEGORY=Custom Casting Tradition,Custom Casting Tradition',
            'PREABILITY:1,CATEGORY=Custom Casting Drawback,Tradition - ' + key,
            *conflicts(key), 'BONUS:ABILITYPOOL|Custom Casting Boon|1',
            'BONUS:VAR|SPHERES_TRADITION_DRAWBACKS|1',
            'DESC:Second selection. ' + description(row),
            'SOURCEPAGE:https://spheresofpower.wikidot.com/casting-traditions#' + row['anchor']]))
    for key, row in sections('Boons').items():
        if key not in TACTICAL_BOONS:
            continue
        tags = ['Tradition - ' + key, 'CATEGORY:Custom Casting Boon', 'COST:2',
                'PREABILITY:1,CATEGORY=Custom Casting Tradition,Custom Casting Tradition',
                'BONUS:VAR|SPHERES_TRADITION_BOONS|1']
        if key == 'Overconsumption':
            tags.append('PREABILITY:1,CATEGORY=Custom Casting Drawback,Tradition - Vampiric Casting')
        if key == 'Virtuoso':
            tags += ['PREABILITY:1,CATEGORY=Custom Casting Drawback,Tradition - Skilled Casting']
            tags += ['!PREABILITY:1,CATEGORY=Custom Casting Drawback,Tradition - ' + other
                     for other in ('Center Of Power', 'Magical Signs', 'Witchmarked')]
        tags += ['DESC:' + description(row) + ' Apply conditional effects only in the published circumstances.',
                 'SOURCEPAGE:https://spheresofpower.wikidot.com/casting-traditions#' + row['anchor']]
        rows.append('\t'.join(tags))
    # Add the reverse restrictions to existing legacy records without changing keys.
    for key in sorted(LEGACY):
        if conflicts(key):
            rows.append('\t'.join(['CATEGORY=Custom Casting Drawback|Tradition - ' + key + '.MOD',
                                   *conflicts(key)]))
    rows += [
        'CATEGORY=Custom Casting Drawback|Tradition - Addictive Casting.MOD\tCOST:2\tBONUS:ABILITYPOOL|Custom Casting Boon|1\tBONUS:VAR|SPHERES_TRADITION_DRAWBACKS|1\tDESC:.CLEAR\tDESC:' + description(drawbacks['Addictive Casting']),
        'CATEGORY=Custom Casting Drawback|Tradition - Vampiric Casting.MOD\tCOST:2\tBONUS:ABILITYPOOL|Custom Casting Boon|1\tBONUS:VAR|SPHERES_TRADITION_DRAWBACKS|1\tDESC:.CLEAR\tDESC:' + description(drawbacks['Vampiric Casting']),
        'CATEGORY=Custom Casting Drawback|Tradition - Bonded Casting.MOD\tDESC:.CLEAR\tDESC:' + description(drawbacks['Bonded Casting']),
    ]
    fortified = ['CATEGORY=Custom Casting Boon|Tradition - Fortified Casting.MOD']
    for stat, selected in (('INT', None), ('WIS', 'Wisdom Casting'), ('CHA', 'Charisma Casting')):
        bonus = 'BONUS:VAR|SPHERES_CASTING_ABILITY|max(0,CON-' + stat + ')'
        if selected:
            bonus += '|PREABILITY:1,CATEGORY=Spheres Casting Ability,' + selected
        else:
            bonus += '|!PREABILITY:1,CATEGORY=Spheres Casting Ability,Wisdom Casting,Charisma Casting'
        fortified.append(bonus)
    rows.append('\t'.join(fortified))
    feat = sections('Boons')['Drawback Feat']
    rows.append('\t'.join([
        'Tradition - Drawback Feat', 'CATEGORY:Custom Casting Boon', 'COST:2',
        'PREABILITY:1,CATEGORY=Custom Casting Tradition,Custom Casting Tradition',
        'MULT:YES', 'STACK:YES', 'CHOOSE:NOCHOICE',
        'BONUS:VAR|SPHERES_TRADITION_BOONS|1',
        'BONUS:ABILITYPOOL|Casting Tradition Drawback Feat|1',
        'DESC:' + description(feat),
        'SOURCEPAGE:https://spheresofpower.wikidot.com/casting-traditions#' + feat['anchor']]))
    embodiment = sections('Boons')['Embodiment']
    rows.append('\t'.join([
        'Tradition - Embodiment', 'CATEGORY:Custom Casting Boon', 'COST:2',
        'PREABILITY:1,CATEGORY=Custom Casting Tradition,Custom Casting Tradition',
        'MULT:YES', 'STACK:NO',
        'CHOOSE:USERINPUT|1|TITLE=Substance embodied',
        'PREVARLT:SPHERES_TRADITION_EMBODIMENT,1',
        'DEFINE:SPHERES_TRADITION_EMBODIMENT|0',
        'BONUS:VAR|SPHERES_TRADITION_EMBODIMENT|1',
        'BONUS:VAR|SPHERES_TRADITION_BOONS|1',
        'DESC:Embodied substance: %1. ' + description(embodiment) + '|%LIST',
        'SOURCEPAGE:https://spheresofpower.wikidot.com/casting-traditions#' + embodiment['anchor']]))
    return '\n'.join(rows) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    output = build()
    if args.write:
        OUTPUT.write_text(output)
    elif OUTPUT.read_text() != output:
        raise ValueError('Generated casting options differ')
    print('PASS: deterministic casting options')


if __name__ == '__main__':
    main()