"""Received Time effects, separate from ownership and casting permission."""


def templates():
    effects = [
        ('Timeline Bridge - Knowledge', ['SKILL|TYPE.Knowledge|floor(%CHOICE/2)|TYPE=Insight'],
         'Knowledge check bonus only. Permission to attempt Knowledge checks '
         'untrained is resolved at the table; this does not grant ranks. Remove '
         'when the effect ends, including when spent for a defensive revelation.'),
        ('Timeline Bridge - Single Attack Defense', ['COMBAT|AC|floor(%CHOICE/2)|TYPE=Insight'],
         'Enable ONLY against the single attack chosen when spending a spell '
         'point and an immediate action to end Timeline Bridge. Remove the '
         'Knowledge effect separately, then disable this bonus after the attack.'),
        ('Timeline Bridge - Single Save', ['SAVE|ALL|floor(%CHOICE/2)|TYPE=Insight'],
         'Enable ONLY for the single saving throw chosen when spending a spell '
         'point and an immediate action to end Timeline Bridge. Remove the '
         'Knowledge effect separately, then disable this bonus after the save.'),
        ('Rapid Response - Initiative', ['COMBAT|INITIATIVE|max(1,floor(%CHOICE/2))|TYPE=Competence'],
         'Initiative bonus only. Surprise-round actions are resolved at the table. '
         'This does not grant evasion or uncanny dodge.'),
        ('Rapid Response - Two Selections', ['SAVE|Reflex|2|TYPE=Competence'],
         'Use only when the caster has selected Rapid Response twice. Do not '
         'combine with the three-selection option. Evasion or improved evasion '
         'is resolved at the table; this supplies only the Reflex bonus.'),
        ('Rapid Response - Three Selections', ['SAVE|Reflex|4|TYPE=Competence'],
         'Use only when the caster has selected Rapid Response three times. '
         'Replaces the two-selection Reflex bonus. Evasion and uncanny dodge '
         'upgrades remain player-managed; no permanent class features are granted.'),
        ('Broken Time', ['COMBAT|TOHIT|-floor(%CHOICE/2)',
                         'SKILL|ALL|-floor(%CHOICE/2)'],
         'Apply only after a failed Will save. Attack rolls and skill checks only; '
         'does not penalize saves, damage or ability scores. Casting requires a '
         'separate concentration check against the caster MSD. Resolve that check '
         'and the new free-action Will save each round at the table.'),
        ('Haste - Attack', ['COMBAT|TOHIT|1+floor(%CHOICE/10)'],
         'Attack bonus only. Apply the separate dodge and movement effects as appropriate.'),
        ('Haste - Dodge', ['COMBAT|AC|1+floor(%CHOICE/10)|TYPE=Dodge',
                           'SAVE|Reflex|1+floor(%CHOICE/10)|TYPE=Dodge'],
         'Disable when dodge bonuses are denied. Does not grant additional attacks.'),
        ('Slow - Penalties', ['COMBAT|TOHIT,AC|-1-floor(%CHOICE/10)',
                              'SAVE|Reflex|-1-floor(%CHOICE/10)'],
         'Apply after the target fails its save. Halve existing movement speeds '
         'separately, minimum 5 feet. Does not automatically apply staggered.'),
        ('Improved Haste - Full Attack', ['COMBAT|ATTACKS|1|TYPE=Enhancement'],
         'Enable ONLY for a full attack while benefiting from Improved Haste. '
         'One extra attack at highest base attack bonus; does not stack with '
         'haste or speed-weapon extra attacks. Do not also use the extra attacks '
         'of opportunity option during this round.'),
        ('Improved Haste - Attacks of Opportunity', [
            'VAR|SPHERES_RECEIVED_IMPROVED_HASTE_AOO|1+floor(%CHOICE/5)'],
         'Additional attacks of opportunity capacity only; expenditure remains '
         'player-managed. Do not use in a round when a full attack gained a '
         'bonus attack from Improved Haste, haste or a similar effect.'),
    ]
    for movement in ('Walk', 'Climb', 'Swim', 'Fly', 'Burrow'):
        effects.append(('Haste - ' + movement,
                        ['MOVEADD|TYPE.' + movement + '|10+10*floor(%CHOICE/5)|TYPE=Enhancement'],
                        'Apply only to an existing ' + movement + ' speed. Does not grant a movement mode.'))
    lines = ['# Generated by tools/spheres_catalog_lst.py; OGC: catalog-OGL.txt']
    for name, bonuses, description in effects:
        lines.append('\t'.join([
            'Time Effect - ' + name, 'VISIBLE:NO',
            *['TEMPBONUS:ANYPC|' + bonus for bonus in bonuses],
            'TEMPVALUE:MIN=1|MAX=100|TITLE=Choose the effect caster level',
            'TEMPDESC:' + description + ' Enter caster level when cast, not recipient level. '
            'Duration, concentration and spell points remain player-managed. Haste and '
            'Slow require an opposed magic skill check to counter each other; do not '
            'simply apply both. Remove when the effect ends.',
            'SOURCEPAGE:https://spheresofpower.wikidot.com/time',
        ]))
    # Adult penalties are cumulative. Apply only the difference, preserving
    # natural aging already represented by the recipient's character sheet.
    adult_ages = (('Young Adult', 0), ('Middle Age', -1), ('Old Age', -3), ('Venerable', -6))
    for original, original_penalty in adult_ages:
        for target, target_penalty in adult_ages:
            if original == target:
                continue
            lines.append('\t'.join([
                'Time Effect - Age - ' + original + ' to ' + target, 'VISIBLE:NO',
                'TEMPBONUS:ANYPC|STAT|STR,DEX,CON|' + str(target_penalty - original_penalty),
                'TEMPDESC:Received Age, changing from ' + original + ' to ' + target +
                '. Apply only if the original age penalties are already represented. '
                'Use one Age transition at a time; replace rather than combine transitions. '
                'Mental scores and permanent age remain unchanged. The caster must be able '
                'to shift the required number of categories (1 plus floor(caster level/5)). '
                'Saving throw, concentration, spell points and expiration remain player-managed. '
                'Remove when the effect ends. Child/youth and object aging are not covered.',
                'SOURCEPAGE:https://spheresofpower.wikidot.com/time',
            ]))
    return '\n'.join(lines) + '\n'