"""Generate Incanter Sphere Specialization records from the pinned Incanter page.

Taking a sphere specialization grants the sphere and its +1 caster level outright
(prerequisite-bearing permanent characteristics); activating it brings the named
abilities into effect in specialization order, gated at their published Incanter
levels. Ability text stays rules text. Destruction is hand-written in
spheres_incanter.lst under the same policy and is skipped here.
"""
import argparse
import json
import re

from spheres import DATA
from spheres_catalog_source import SNAPSHOTS

OUTPUT = DATA / 'spheres_incanter_sphere_specializations.lst'
CATEGORIES = DATA / 'spheres_categories_incanter_specializations.lst'
EXISTING = {'Destruction'}
TYPES = {'Su': 'Supernatural', 'Sp': 'SpellLike', 'Ex': 'Extraordinary'}
ABILITY = re.compile(r'^([A-Z][^:\n]{2,60}?)(?: \((Su|Sp|Ex)\))?:')
ORDINAL = re.compile(r'\b(\d+)(?:st|nd|rd|th) level')


def sphere_name(heading):
    name = re.sub(r'\s*\[[^]]+\]', '', heading).strip()
    return re.sub(r'^Incanter Sphere Specialization:\s*', '', name).strip()


def var_name(sphere):
    return re.sub(r'[^A-Z]', '', sphere.upper())


def sphere_sections():
    source = json.loads((SNAPSHOTS / 'incanter.json').read_text())
    rows = source['sections']
    start = next(i for i, row in enumerate(rows)
                 if row['heading'].startswith('List of Sphere Specializations'))
    result = []
    for row in rows[start + 1:]:
        if row['level'] <= 2:
            break
        if row['level'] == 3:
            result.append((sphere_name(row['heading']), row))
    return result


def abilities(text):
    """Split a sphere's rules text into named abilities with a starting level."""
    found = []
    for line in text.split('\n'):
        match = ABILITY.match(line.strip())
        if match and (not found or match.group(1) not in [a[0] for a in found]):
            found.append([match.group(1).strip(), match.group(2), line.strip()])
        elif found:
            found[-1][2] += ' ' + line.strip()
    result = []
    for name, kind, body in found:
        levels = [int(n) for n in ORDINAL.findall(body)]
        result.append((name, TYPES.get(kind, 'Supernatural'), min(levels) if levels else 1, body))
    return result


def description(text):
    return ' '.join(text.replace('|', '/').replace('%', ' percent')
                    .replace('(', '[').replace(')', ']').split())


def ability_key(sphere, name):
    return 'Incanter ' + sphere + ' ' + name


def pool_key(sphere):
    return 'Incanter ' + sphere + ' Specialization Talent'


def build():
    rows = ['# Generated by tools/spheres_incanter_specializations.py from the pinned',
            '# Incanter page. Ability text stays rules text; level gates, the +1 sphere',
            '# caster level and the already-possessed alternative are applied. Destruction',
            '# remains hand-written in spheres_incanter.lst.']
    categories = ['# Generated by tools/spheres_incanter_specializations.py.']
    for sphere, row in sphere_sections():
        if sphere in EXISTING:
            continue
        parsed = abilities(row['text'])
        source = 'SOURCEPAGE:https://spheresofpower.wikidot.com/incanter#' + row['anchor']
        subs = [s['heading'].replace('Sub-Specialization: ', '')
                for s in sphere_subheadings(sphere)]
        note = ''
        if subs:
            note = (' Sub-specializations trade abilities: ' + '; '.join(subs) + '.')
        # PCGen evaluates a conditional grant against the post-grant state, so "do I
        # already have this sphere?" cannot be detected automatically. The published
        # alternative is therefore an explicit paired choice, mirroring the existing
        # "Second Selection" records: the base record grants the sphere, the
        # "- Already Known" record grants one talent of that sphere instead.
        rows.append('\t'.join([
            'Sphere Specialization (' + sphere + ')',
            'CATEGORY:Incanter Specialization', 'TYPE:IncanterSpecialization', 'COST:3',
            'PREVAREQ:SPHERES_INCANTER_LEVEL,1',
            '!PREABILITY:1,CATEGORY=Incanter Specialization,Sphere Specialization ('
            + sphere + ') - Already Known',
            'BONUS:VAR|SPHERES_INCANTER_SPECIALIZATION_POINTS|3',
            'ABILITY:Spheres Magic Talent|AUTOMATIC|' + sphere + ' Sphere',
            'BONUS:VAR|SPHERES_CL_' + var_name(sphere) + '|1',
            'DESC:Gain the ' + sphere + ' sphere as a bonus sphere and +1 caster level with'
            ' it; its specialization abilities come into effect in specialization order,'
            ' gated by level. Select the "- Already Known" record instead if you already'
            ' possess the ' + sphere + ' sphere.' + note, source]))
        rows.append('\t'.join([
            'Sphere Specialization (' + sphere + ') - Already Known',
            'CATEGORY:Incanter Specialization', 'TYPE:IncanterSpecialization', 'COST:3',
            'PREVAREQ:SPHERES_INCANTER_LEVEL,1',
            '!PREABILITY:1,CATEGORY=Incanter Specialization,Sphere Specialization ('
            + sphere + ')',
            'BONUS:VAR|SPHERES_INCANTER_SPECIALIZATION_POINTS|3',
            'BONUS:ABILITYPOOL|' + pool_key(sphere) + '|1',
            'BONUS:VAR|SPHERES_CL_' + var_name(sphere) + '|1',
            'DESC:Take this only if you already possess the ' + sphere + ' sphere: you'
            ' instead gain one ' + sphere + ' talent of your choice, plus +1 caster level'
            ' with that sphere and its specialization abilities.' + note, source]))
        categories.append(
            f'ABILITYCATEGORY:{pool_key(sphere)}\tCATEGORY:Spheres Magic Talent'
            f'\tTYPE:SpheresBasicTalent.{sphere}\tEDITABLE:YES\tEDITPOOL:NO'
            f'\tFRACTIONALPOOL:NO\tVISIBLE:QUALIFY\tPOOL:0'
            f'\tPLURAL:{sphere} Specialization Talents\tDISPLAYLOCATION:Spheres')
        gates = []
        by_level = {}
        for name, kind, level, _body in parsed:
            by_level.setdefault(level, []).append(name)
        for level in sorted(by_level):
            gates.append('ABILITY:Special Ability|AUTOMATIC|'
                         + '|'.join(ability_key(sphere, n) for n in by_level[level])
                         + '|PREVARGTEQ:SPHERES_INCANTER_LEVEL,' + str(level))
        rows.append('\t'.join([
            'Active Sphere Specialization (' + sphere + ')',
            'CATEGORY:Incanter Active Specialization', 'TYPE:IncanterActive', 'COST:2',
            'PREMULT:1,[PREABILITY:1,CATEGORY=Incanter Specialization,Sphere Specialization ('
            + sphere + ')],[PREABILITY:1,CATEGORY=Incanter Specialization,Sphere'
            ' Specialization (' + sphere + ') - Already Known]', *gates, source]))
        for name, kind, level, body in parsed:
            rows.append('\t'.join([
                ability_key(sphere, name), 'CATEGORY:Special Ability', 'TYPE:' + kind,
                'DESC:' + description(body)
                + ' Begins at Incanter level ' + str(level) + '.', source]))
    return '\n'.join(rows) + '\n', '\n'.join(categories) + '\n'


def sphere_subheadings(sphere):
    source = json.loads((SNAPSHOTS / 'incanter.json').read_text())
    rows = source['sections']
    start = next(i for i, r in enumerate(rows)
                 if r['level'] == 3 and sphere_name(r['heading']) == sphere)
    result = []
    for row in rows[start + 1:]:
        if row['level'] <= 3:
            break
        if row['level'] == 4 and 'Sub-Specialization' in row['heading']:
            result.append(row)
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    text, categories = build()
    if args.write:
        OUTPUT.write_text(text)
        CATEGORIES.write_text(categories)
    else:
        for path, written in ((OUTPUT, text), (CATEGORIES, categories)):
            if not path.is_file() or path.read_text() != written:
                raise ValueError('Generated Incanter specializations differ: ' + path.name)
    print('PASS: deterministic Incanter sphere specializations')


if __name__ == '__main__':
    main()
