"""Generate PCGen basic-sphere records from the pinned, bounded source manifest.

Rules text is Open Game Content; see data/spheres/catalog-OGL.txt.
Only explicit overrides automate effects. Tactical actions remain sheet rules.
"""
import argparse
import json
import re

from spheres_catalog import inventory
from spheres_catalog_source import ROOT, SNAPSHOTS

DATA = ROOT / "data/spheres"
LEGACY = {"Admixture", "Searing Blast", "Epicenter", "Gather Energy"}
PACKAGES = {
    "athletics": ("Climb", "Fly", "Leap", "Run", "Swim"),
    "alchemy": ("Formulae", "Poison"),
    "beastmastery": ("Handle Animal", "Ride"),
    "guardian": ("Challenge", "Patrol"),
    "leadership": ("Cohort", "Followers"),
    "nature": ("Air", "Earth", "Fire", "Metal", "Plant", "Water"),
    "tinker": ("Augmentation", "Computation", "Modification", "Transmission", "Transportation"),
    "pilot": ("Naval", "Stellar", "Terrestrial"),
}
EXPAND = {"athletics": "Expanded Training", "alchemy": "Master Chemist",
          "beastmastery": "Extra Beastmastery Package", "guardian": "Expanded Guardian",
          "leadership": "Expanded Leadership", "nature": "Expanded Geomancing",
          "tinker": "Expanded Tinkering", "pilot": "Expanded Piloting"}
SKILLS = {"alchemy": "Craft (Alchemy)", "fencing": "Bluff", "gladiator": "Intimidate",
          "scoundrel": "Sleight of Hand", "scout": "Stealth", "trap": "Craft (Traps)",
          "warleader-sphere": "Diplomacy", "leadership": "Diplomacy"}


def token(name):
    return re.sub(r"[^A-Za-z0-9]", "", name)


def text(value):
    # DESC parses parentheses as delimiters; published prose includes unmatched ones.
    return " ".join(value.replace("|", "/").replace("%", " percent")
                    .replace("(", "[").replace(")", "]").split())


def category(row):
    return "Spheres Magic Talent" if row["system"] == "power" else "Spheres Combat Talent"


def key(row, talent):
    if row["slug"] == "destruction" and talent["name"] in LEGACY:
        return talent["name"]
    return row["sphere"] + " - " + talent["name"].replace(",", "")


def repeat_limit(talent):
    """Conservative, source-explicit repeatability; no inference from effect scaling."""
    rule = talent["text"]
    phrase = r"(?:take|select|gain) this talent (?:a |an |up to |a total of )?"
    if re.search(phrase + r"(?:second time|twice|two times)", rule, re.I):
        return 2
    for word, count in (("two",2),("three",3),("3",3),("4",4),("5",5)):
        if re.search(phrase + word + r" times", rule, re.I):
            return count
    if re.search(phrase + r"(?:multiple times|any number of times|as many times)", rule, re.I):
        return 99
    return 1


def build():
    rows = inventory()
    overrides = json.loads((DATA / "catalog-mechanics.json").read_text())
    categories, packages, output = [], [], {}
    review = []
    for row in rows:
        name, slug, cat = row["sphere"], row["slug"], category(row)
        ident = token(name)
        prefix = "SPHERES_" + ident.upper()
        base = name + " Sphere"
        lines = ["# Generated by tools/spheres_catalog_lst.py; OGC: catalog-OGL.txt",
                 "# " + row["url"]]
        base_tags = [base, "CATEGORY:" + cat, "TYPE:SpheresBaseSphere." + ident,
                     "PREVARGTEQ:" + ("SPHERES_CASTER_LEVEL,1" if row["system"] == "power" else "SPHERES_COMBAT_TALENTS,1"),
                     "DEFINE:" + prefix + "_TALENTS|0", "BONUS:VAR|" + prefix + "_TALENTS|1"]
        if row["system"] == "power" and slug != "destruction":
            base_tags.extend(["DEFINE:SPHERES_CL_" + ident.upper() + "|SPHERES_CASTER_LEVEL",
                "DEFINE:SPHERES_DC_" + ident.upper() + "|10+floor(SPHERES_CL_" + ident.upper() + "/2)+SPHERES_CASTING_ABILITY"])
        if row["system"] == "might":
            base_tags.extend(["DEFINE:SPHERES_BAB_" + ident.upper() + "|BAB",
                "DEFINE:SPHERES_DC_" + ident.upper() + "|10+floor(SPHERES_BAB_" + ident.upper() + "/2)+SPHERES_PRACTITIONER_MOD"])
        if slug in SKILLS:
            base_tags.append("BONUS:SKILLRANK|" + SKILLS[slug] + "|min(TL,5*" + prefix + "_TALENTS)|TYPE=SpheresTraining")
        if slug == "equipment-sphere":
            base_tags.append("BONUS:ABILITYPOOL|Spheres Equipment Bonus Talent|1")
            categories.append("\t".join(["ABILITYCATEGORY:Spheres Equipment Bonus Talent", "CATEGORY:" + cat,
                "TYPE:EquipmentTalent", "EDITABLE:YES", "EDITPOOL:NO", "FRACTIONALPOOL:NO", "VISIBLE:QUALIFY",
                "POOL:0", "PLURAL:Equipment Free Talent", "DISPLAYLOCATION:Spheres"]))
        if slug in PACKAGES:
            package_cat = "Spheres " + name + " Package"
            var = prefix + "_PACKAGES"
            base_tags.extend(["DEFINE:" + var + "|0", "BONUS:VAR|" + var + "|1"])
            categories.append("\t".join(["ABILITYCATEGORY:" + package_cat, "CATEGORY:" + package_cat,
                "EDITABLE:YES", "EDITPOOL:NO", "FRACTIONALPOOL:NO", "VISIBLE:QUALIFY", "POOL:" + var,
                "PLURAL:" + name + " Packages", "DISPLAYLOCATION:Spheres"]))
            source = json.loads((SNAPSHOTS / (slug + ".json")).read_text())["sections"]
            for choice in PACKAGES[slug]:
                matching = [s for s in source[:60] if s["heading"].lower() == choice.lower()]
                desc = matching[0]["text"] if matching else "See the base sphere's " + choice + " package rules."
                package_tags = [name + " Package - " + choice, "CATEGORY:" + package_cat,
                    "TYPE:" + ident + "Package." + token(choice), "PREABILITY:1,CATEGORY=" + cat + "," + base,
                    "DESC:" + text(desc)]
                skill = ({"Climb":"Climb", "Fly":"Fly", "Leap":"Acrobatics", "Run":"Acrobatics", "Swim":"Swim"}.get(choice)
                         if slug == "athletics" else choice if slug == "beastmastery" else None)
                if skill:
                    package_tags.append("BONUS:SKILLRANK|" + skill + "|min(TL,5*" + prefix + "_TALENTS)|TYPE=SpheresTraining")
                packages.append("\t".join(package_tags))
        base_tags += [re.sub(r"\bBAB\b", "SPHERES_BAB_" + ident.upper(), tag)
                      if row["system"] == "might" else tag for tag in overrides.get(base, [])]
        base_tags += ["DESC:" + text(row["base"]) + " Automation is partial; consult docs/sphere-catalog.md. Unautomated rules must be applied manually.",
                      "SOURCEPAGE:" + row["url"]]
        if slug != "destruction":
            lines.append("\t".join(base_tags))
        for talent in row["talents"]:
            name_key = key(row, talent)
            if slug == "destruction" and talent["name"] in LEGACY:
                continue
            tags = [name_key, "CATEGORY:" + cat, "TYPE:SpheresBasicTalent." + ident,
                    "PREABILITY:1,CATEGORY=" + cat + "," + base,
                    "BONUS:VAR|" + prefix + "_TALENTS|1"]
            if slug == "equipment-sphere":
                tags[2] += ".EquipmentTalent"
            limit = repeat_limit(talent)
            if name_key in overrides and any(t.startswith("MULT:") for t in overrides[name_key]):
                limit = 1
            if limit > 1:
                counter = prefix + "_" + token(talent["name"]).upper() + "_COUNT"
                tags += ["MULT:YES", "STACK:YES", "CHOOSE:NOCHOICE", "DEFINE:" + counter + "|0",
                         "BONUS:VAR|" + counter + "|1"]
                if limit < 99:
                    tags += ["PREVARLT:" + counter + "," + str(limit)]
            if slug in PACKAGES:
                inside = " ".join(re.findall(r"\(([^)]*)\)", talent["heading"])).lower()
                matches = [p for p in PACKAGES[slug] if p.lower() in re.split(r", | or ", inside)]
                if matches:
                    tags.append("PREABILITY:1,CATEGORY=Spheres " + name + " Package," + ",".join(name + " Package - " + p for p in matches))
                if talent["name"] == EXPAND[slug]:
                    tags.append("BONUS:VAR|" + prefix + "_PACKAGES|" + ("2" if slug in ("tinker", "athletics") else "1"))
                    tags.append("PREVARLT:" + prefix + "_PACKAGES," + str(len(PACKAGES[slug])))
            match = re.search(r"^Prerequisites?: Caster level (\d+)", talent["text"])
            if match:
                tags.append("PREVARGTEQ:SPHERES_CASTER_LEVEL," + match[1])
            tags += overrides.get(name_key, [])
            tags += ["DESC:" + text(talent["text"]) + " Automation is partial; consult docs/sphere-catalog.md. Unautomated rules must be applied manually.",
                     "SOURCEPAGE:" + talent["url"]]
            lines.append("\t".join(tags))
            review.append({"key": name_key, "sphere": name, "repeat_limit": limit,
                           "mechanics": overrides.get(name_key, []),
                           "prerequisites": [t for t in tags if t.startswith("PRE")]})
        output[f"spheres_{row['system']}_{slug}.lst"] = "\n".join(lines) + "\n"
    output["spheres_categories_catalog.lst"] = "\n".join(categories) + "\n"
    output["spheres_catalog_packages.lst"] = "\n".join(packages) + "\n"
    return output, review


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    files, review = build()
    if args.write:
        for name, content in files.items():
            (DATA / name).write_text(content, encoding="utf-8")
        (DATA / "catalog-review.json").write_text(json.dumps(review, indent=2) + "\n")
        legal = json.loads((SNAPSHOTS / "legal-start.json").read_text())["sections"][0]["text"]
        (DATA / "catalog-OGL.txt").write_text("Sphere rules in the generated catalog are Open Game Content.\nSource: https://spheresofpower.wikidot.com/legal:start\n\n" + legal + "\n")
    else:
        for name, content in files.items():
            if (DATA / name).read_text() != content:
                raise ValueError("Generated file differs: " + name)
    print(f"PASS: {len(files)} deterministic catalog files; {len(review)} additional talents")


if __name__ == "__main__":
    main()